Hw 4 replication
polis-vk/2022-highload-dht pull request #100
Opened 2022-10-26 18:56 UTC by T-y-c-o-o-n

2022-10-31 11:51 UTC, incubos requested changes
Есть ряд замечаний и вопросов.

2022-10-31 11:51 UTC, incubos commented on src/main/java/ok/dht/test/siniachenko/service/TycoonService.java
> +        return httpClient.sendAsync(
На каком пуле потоков будет выполняться?

2022-10-31 11:51 UTC, incubos commented on src/main/java/ok/dht/test/siniachenko/service/ReplicatedRequestAggregator.java
> +                return null;
Что это за случай такой?

2022-10-31 11:51 UTC, incubos commented on src/main/java/ok/dht/test/siniachenko/service/TycoonService.java
> +        byte[][] bodies = new byte[ack][];
`bodies` заполняют из разных потоков, верно? Как гарантируется потокобезопасность?

2022-10-31 11:51 UTC, incubos commented on src/main/java/ok/dht/test/siniachenko/service/ReplicatedRequestAggregator.java
> +            if (bodies[replicaAnswered] != null && bodies[replicaAnswered].length != 0) {
Почему мы проверяем и на `null`, и на пустой массив байт?

2022-10-31 11:51 UTC, incubos commented on src/main/java/ok/dht/test/siniachenko/service/ReplicatedRequestAggregator.java
> +            maxTimeStampReplica == -1 || bodies[maxTimeStampReplica] == null
Что означает первое условие `maxTimeStampReplica == -1`? Мы не получили ни одного ответа и при этом возвращаем `NOT_FOUND`?

2022-10-31 11:51 UTC, incubos commented on src/main/java/ok/dht/test/siniachenko/service/EntityServiceReplica.java
> +                default -> new Response(Response.METHOD_NOT_ALLOWED, Response.EMPTY);
Мы разве не проверили это раньше?

2022-10-31 11:51 UTC, incubos commented on src/main/java/ok/dht/test/siniachenko/service/EntityServiceReplica.java
> +            TycoonHttpServer.sendResponse(session, response);
Неожиданная цепочка вызовов (сервис -> сервер) -- текут абстракции.

2022-10-31 11:51 UTC, incubos commented on src/main/java/ok/dht/test/siniachenko/service/EntityServiceReplica.java
> +                return new Response(Response.GONE, value);
Для чего нам нужен ещё один код ответа `GONE`, если мы анализируем тело и читаем delete marker из него?

2022-10-31 11:51 UTC, incubos commented on src/main/java/ok/dht/test/siniachenko/service/TycoonService.java
> +    private CompletableFuture<HttpResponse<byte[]>> proxyRequest(Request request, String idParameter, String nodeUrl) {
Суть текущего этапа -- реализовать **корректную** синхронную репликацию. Асинхронная реализация (следующий этап) является отдельной нефункциональной фичей и должна делаться в отдельном PR. Это применимо и к инженерной практике: никто не согласиться ревьюить PR, в котором реализовано сразу несколько фич. Поэтому предлагаю упростить решение, а асинхронный наработки использовать на следующем этапе.

2022-10-31 11:51 UTC, incubos commented on src/main/java/ok/dht/test/siniachenko/service/TycoonService.java
> +                    nodeRequestsTimeouts.compute(nodeUrlByKey, (url, t) -> Math.min(t / 2, MAX_TIMEOUT_MILLIS));
В чём физический смысл `nodeRequestsTimeouts` и арифметики с таймаутами? Нужны комментарии.

2022-10-31 11:51 UTC, incubos commented on src/main/java/ok/dht/test/siniachenko/service/TycoonService.java
> +    public void executeRequest(Request request, HttpSession session, String id) {
Большой и сложный метод, в котором и сетевое общение, и обработка запросов, и всё это конкурентно -- нужен рефакторинг.

2022-11-01 16:47 UTC, T-y-c-o-o-n commented on src/main/resources/logback.xml
> -        <appender-ref ref="console"/>
откатил

2022-11-01 16:47 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/service/TycoonService.java
> +            String ackParameter = request.getParameter("ack=");
Сделал EntityServiceCoordinator#getIntParameter

2022-11-01 16:47 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/service/TycoonService.java
> +            request.setBody(Utils.withCurrentTimestampAndFlagDeleted(new byte[0], true));
Теперь это происходит более явно и в самих методах handlePut и handleDelete

2022-11-01 16:47 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/service/TycoonService.java
> +        return httpClient.sendAsync(
сделал httpClient.send

2022-11-01 16:47 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/service/TycoonService.java
> +        return httpClient.sendAsync(
выполнялось бы оно на дефолтном пуле HttpClient-а, вроде CachedThreadPool или уже ForkJoinPool

2022-11-01 16:47 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/service/ReplicatedRequestAggregator.java
> +                return null;
Это был случай, когда нужные ack ответов уже пришли, и теперь приходят остатки запросов, но ответ уже отправлен

2022-11-01 16:47 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/service/ReplicatedRequestAggregator.java
> +                return null;
Сейчас я убрал асинхронное взаимодействие инстансов и это ушло

2022-11-01 16:47 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/service/TycoonService.java
> +        byte[][] bodies = new byte[ack][];
Там был HappendBefore за счет того, что разные потоки писали строго в разные ячейки массива, а чтения происходили после синхронизации потоков через CompletableFuture. Сейчас это уйдет в другой пулл реквест с 5 домашкой

2022-11-01 16:47 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/service/ReplicatedRequestAggregator.java
> +            if (bodies[replicaAnswered] != null && bodies[replicaAnswered].length != 0) {
скорее всего проверка на  null была лишней, а сейчас это есть в handleGet, потому что там размер bodies - from - и null сигнализирует, что реплика не ответила

2022-11-01 16:47 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/service/ReplicatedRequestAggregator.java
> +            maxTimeStampReplica == -1 || bodies[maxTimeStampReplica] == null
скорее всего это был невозможный случай, либо ошибка в алгоритме проверки, что пришло достаточно или недостаточно ответов. Сейчас это ушло и исправится в ПР по 5 домашке

2022-11-01 16:47 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/service/TycoonService.java
> +    public void executeRequest(Request request, HttpSession session, String id) {
Порефакторил и вынес в EntityServiceCoordinator#replicateRequestAndAwait

2022-11-01 16:47 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/service/TycoonService.java
> +                    nodeRequestsTimeouts.compute(nodeUrlByKey, (url, t) -> Math.min(t / 2, MAX_TIMEOUT_MILLIS));
Это была моя идея уменьшать занятость потоков на ожидании ответа от ноды. Но идея была скорее от бедности. Она состояла в том, что в случае неуспеха мы уменьшаем таймаут ожидания и постепенно потоки будут меньше ждать ответа от ноды.

2022-11-01 16:47 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/service/TycoonService.java
> +    private CompletableFuture<HttpResponse<byte[]>> proxyRequest(Request request, String idParameter, String nodeUrl) {
Выпилил асинхронную часть. Сделаю её в отдельном ПРе

2022-11-02 09:01 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/service/EntityServiceReplica.java
> +            TycoonHttpServer.sendResponse(session, response);
Изменил, теперь Response возвращается из метода, а не посылается прям в нём

2022-11-02 09:01 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/service/EntityServiceReplica.java
> +                return new Response(Response.GONE, value);
Убрал

2022-11-02 13:01 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/rendezvoushashing/NodeMapper.java
> +    private int hash(byte[] key, String node) {
поменял на консистентное хэширование

2022-11-02 13:01 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/rendezvoushashing/NodeMapper.java
> +                result = (result + ((j << 2) == 0 ? ~c : c) * b) % mod;
исвользую теперь SHA-256

2022-11-02 13:01 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/rendezvoushashing/NodeMapper.java
> +        mod = nodeUrls.size() * 1000;
убрал модуль

2022-11-02 13:02 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/rendezvoushashing/NodeMapper.java
> +        Arrays.sort(hashesAndNodes);
Новый подход теперь за log(n)

2022-11-02 18:16 UTC, T-y-c-o-o-n reviewed
пофиксил нахождение нод реплик и так же добавил о\граничения для потоков на ноду

2022-11-02 18:16 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/service/TycoonService.java
> +                    nodeRequestsTimeouts.compute(nodeUrlByKey, (url, t) -> Math.min(t / 2, MAX_TIMEOUT_MILLIS));
Сейчас я для ограничения потоков для ноды сделал отдельный NodeTaskManager

2022-11-02 21:21 UTC, T-y-c-o-o-n commented
Изначально написал в 4 домашке сразу реализацию 5 (а именно асинхронное взаимодействие через CompletableFuture
и ожидание только `ack` запросов, а не всех). Но пришлось переделывать и удалять это, а добавлять синхронное взаимодействие.
Но поскольку я сделал реализацию 5 домашки ещё за неделю до её бонусного дедлайна, а именно до дедлайна 4,
то хотелось бы возможности бонусных баллов за это, учитывая то, сколько проблем было распилить асинхронную реализацию
на синхронную. Двойная работа получилась, если не больше.

2022-11-03 14:08 UTC, Artyomcool commented
Напомню, что двойную работу вы себе придумали сами - делать в одном PR больше, чем требует этот PR, плохая инженерная практика, что и отметил Вадим)
На счёт бонусных баллов посмотрим по корректности.

2022-11-26 15:16 UTC, Artyomcool approved these changes
-4 балла от максимума

2022-11-26 15:16 UTC, Artyomcool commented on src/main/java/ok/dht/test/siniachenko/nodemapper/NodeMapper.java
> +    private final ThreadLocal<MessageDigest> hashAlgorithm;
ThreadLocal работает через... большое количество индерекций.
Лучше написать свою мапу потока, если на то пошло.
Но возможно лучше вообще не кэшировать, лучше это профилировать.

2022-11-26 15:16 UTC, Artyomcool commented on src/main/java/ok/dht/test/siniachenko/nodemapper/NodeMapper.java
> +        int index = Arrays.binarySearch(shards, new Shard(null, keyHash));
вы не хотите аллокаций в таких местах

2022-11-26 15:16 UTC, Artyomcool commented on src/main/java/ok/dht/test/siniachenko/nodemapper/NodeMapper.java
> +            return Integer.compare(hash, shard.hash);
comparable по одному полю выглядит так себе, рекомендую использовать компаратор

2022-12-20 15:55 UTC, closed without merging