Stage3 Lutsenko Dmitrii
polis-vk/2022-highload-dht pull request #100
Opened 2022-10-11 19:57 UTC by LutsenkoDm

2022-10-12 14:13 UTC, Fedoresko requested changes
Надо пофиксить кое что и ответить на вопросы.

2022-10-12 14:13 UTC, Fedoresko commented on src/main/java/ok/dht/test/lutsenko/reports/Stage3-report.md
> +заменив http протокол на другой, более эффективный, например, RPC или JSON-RPC. Также около 15% CPU уходит на метод
А почему JSON-RPC, скажем, будет более эффективным?

2022-10-12 14:13 UTC, Fedoresko commented on src/main/java/ok/dht/test/lutsenko/reports/Stage3-report.md
> +бывает пустая. Увеличить rate до значений когда она постоянно заполнена не получиться, так как сервер тогда не выдержит
А как может быть так, что очередь пустая, а rate не увеличить? Это может быть только если положить запрос в очередь занимает всегда больше времени, чем идет обработка воркерами. Прошу пояснить.

2022-10-13 20:18 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/DemoService.java
> +                int nodePosition = Math.abs((url + Math.atan(Math.log(i * (i + HASH_SPACE)))).hashCode() % HASH_SPACE);
Эта функция была нужна для того, чтобы сделать распределение хэшей равномерным, так как использовался стандартный hashCode(), значения которого при url + i и url + i + 1 отличались на 1 только последним символом. Заменил на murmur3 из one.nio, взял его так как он  дает хорошее распределение для похожих строк, соответственно эту функцию убрал, и эффективнее стандартного hashCode().

2022-10-13 20:20 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/DemoService.java
> +                virtualNodes.put(nodePosition, url);
Не совсем не попадет ни один ключ, будет такая ситуация, что более поздние ноды перезапишут значение при коллизии и ключи будут отправляться на них. Добавил обработку ситуации коллизий.

2022-10-13 20:30 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/DemoService.java
> +    private final NavigableMap<Integer, String> virtualNodes = new TreeMap<>();
Массив в данном случае усложнит количество кода и его читаемость. Например, всегда надо будет держать в голове что он отсортирован и придется написать лишний функционал, для работы с ним , который уже предоставляет TreeMap. Читающий код сразу будет видеть, что данная коллекция отсортирована и будет легче понять для чего она нужна и как устроена. Да, мапа медленнее массива, но в данном случае это не важно, так как на профилях операция ceilingEntry, единственная, кроме заполнения мапы занимает 0.14% при PUT и ее даже нет в профилях при GET запросах при 100 виртуальных нодах и 24 узлах. Таким образом оптимизация с использованием массива не стоит того чтобы писать свой велосипед, который усложнит читаемость и понятность кода и который эквивалентен 2 строчкам кода с мапой. + Если когда-нибудь понадобиться добавить поддержку добавления ноды, то массив придется пересоздавать на каждую новую ноду.

2022-10-13 20:33 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/DemoService.java
> +        Files.createDirectories(daoPath);
Перенес создание в DaoConfig. Полностью убрать из сервиса формирование пути для dao не получситься, так как папка с dao должна находиться внутри папки сервиса, то есть надо или передавать путь к папке сервиса из конфига в dao или формировать путь для dao на месте, я выбрал 2-й вариант, иначе тесты не пройдут

2022-10-13 20:36 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/DemoService.java
> +        if (keyLocationUrl.equals(config.selfUrl())) {
Переделал на номера нод. Но мне кажется тут сравнение не сильно критично, так как у нас урлы, а они всегда небольшой длины, а номера нод надо все равно мапить с урлом ноды, но неприятно, что в мапе виртуальных нод на каждую позицию ноды придется записывать в value урл, а это лишнее и с номерами будет получше.

2022-10-13 20:47 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/DemoService.java
> +        HttpResponse<byte[]> getResponse = sendGetRequest(keyLocationUrl, id).get();
Сделал следующим образом: если нода недоступна (или это сама нода куда пришел исходный запрос но у нее отвалилось dao), то ее номер добавляется в set, в который смотрим при обработке запроса (еще до проксирования или похода в dao) и если ключ относиться к ноде из этого set, то отвечаем SERVICE_UNAVAILABLE. Так произойдет даже при Timeout и мы не узнаем, если эта нода оживет, но сервер будет работать. Можно сделать счетчик timeout-в и при его достижении только добавлять ноду в set недоступных нод (но timeout сейчас довольно большой и в общем случае он не будет относительно маленьким, поэтому мне кажется приемлемо помечать добавлять ноду в недоступные даже при одном таймауте), а также сделать отдельный поток в котором будем опрашивать ноды раз в промежуток времени, например раз в минуту, только из этого set. Но это выходит за рамки данного stage + я думаю лучше сделать это в stage с репликацией.

2022-10-13 20:52 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/Stage3-report.md
> +время для выполнения бизнес-логики запроса сопоставимо с временем похода по сети или больше его, то шардирование
В этих строчках как раз про время запроса, то есть имеется в виду, что если PUT при 1 узле мы выполняем за 10ms, а если его проксируем, то за 20ms из-за времени на сеть, то будет медленнее с кластером чем одним уpлом. Но если GET  на сервисе с 1 узлом выполняется за 100ms, а по сети можем сходить за ним за 20ms, то кластер выигрывает. Выше, где написано про rate дописал и разделил, чтобы не путалось с тем, где про latency,

2022-10-13 20:57 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/Stage3-report.md
> +в десятках миллисекунд. При 10 и 24 узлах в кластере показатели как по среднему и максимальному времени, так и по
Добавил в отчете. Если коротко, то при 1 и 2 узлам данных на 1 узле больше чем page cache, а при 4 уже меньше и там идет чтение условно из памяти. Даже не смотря на это, суть данного эксперимента была в том, чтобы показать эффективность кластера по сравнению с 1 узлом, поэтому такой "эффект" неприятен, но главная идея эксперимента не пострадала.

2022-10-13 21:00 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/Stage3-report.md
> +заменив http протокол на другой, более эффективный, например, RPC или JSON-RPC. Также около 15% CPU уходит на метод
В общем, да особо не лучше. Убрал из отчета.

2022-10-13 21:02 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/Stage3-report.md
> +бывает пустая. Увеличить rate до значений когда она постоянно заполнена не получиться, так как сервер тогда не выдержит
Да,  ситуации с пустой очередью здесь не будет, немного напутал из-за предыдущего stage, там была такая проблема. Дело здесь только в конкуренции между потоками. В отчете исправил.

2022-10-13 21:04 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/DemoService.java
> +                int nodePosition = Math.abs((url + Math.atan(Math.log(i * (i + HASH_SPACE)))).hashCode() % HASH_SPACE);
Все фиксы в коде были залиты до лекции: коммит Fixes due to comments. 
После только поправил отчет и ответил на вопросы.

2022-10-13 21:14 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/DemoService.java
> +        HttpResponse<byte[]> getResponse = sendGetRequest(keyLocationUrl, id).get();
Также добавил get по с timeout-м для completableFuture для получения ответа от проксируемых нод

2022-10-14 11:41 UTC, Fedoresko commented on src/main/java/ok/dht/test/lutsenko/reports/Stage3-report.md
> +заменив http протокол на другой, более эффективный, например, RPC или JSON-RPC. Также около 15% CPU уходит на метод
Ну а в Http есть pipelining, который уже поддерживается по дефолту, и не очевидно в чем сравнительная сложность http. Тем, что в нем есть заголовки? Но в наших запросах их почти нет. В общем, тут надо запилить и сравнительно потестить. В целом сериализация json не кажется чем-то "легковесным".

2022-10-14 12:00 UTC, Fedoresko commented on src/main/java/ok/dht/test/lutsenko/service/DemoService.java
> +            unavailableNodes.add(keyLocationNodeNumber);
А в данном случае любой Exception означает, что нода недоступна? Мне кажется, тут требуется какой-то более тонкий подход. Могут быть разные ошибки, и в принципе если есть какие-то проблемы с DAO не уверен, что хорошая идея смешивать эту ситуацию с недоступностью другой ноды. Хотя бы потому что, если кидается exception при чтении с диска, например, там нет таймаутов, и висеть воркер не будет. Проблема очевидно совсем другая, и решение должно быть иным.

2022-10-14 12:02 UTC, Fedoresko commented on src/main/java/ok/dht/test/lutsenko/service/DemoService.java
> +            unavailableNodes.add(keyLocationNodeNumber);
Да, и удалять ноды из unavailableNodes надо хоть каким-то способом. Оставлять их там навсегда - ну это вообще бред. Пусть хотя бы удаляются оттуда через какой-то промежуток времени, как самый простой и очевидный вариант.

2022-10-14 12:09 UTC, Fedoresko commented on src/main/java/ok/dht/test/lutsenko/reports/Stage3-report.md
> +время для выполнения бизнес-логики запроса сопоставимо с временем похода по сети или больше его, то шардирование
На самом деле, если посмотрите, то воркеры по-прежнему блокируются проксируемыми запросами. Это значит что пул воркеров расходуется на эти соединения (а их у вас и так очень мало). Это нехорошо.  Я считаю, что это надо переделать в таком виде не приму.

2022-10-14 12:11 UTC, Fedoresko requested changes
Переделайте так, чтобы воркеры не блокировались проски запросами.

2022-10-16 11:24 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/DemoService.java
> +            unavailableNodes.add(keyLocationNodeNumber);
Разделил обработку для dao, Timeout-ов при ответе от другой ноды, сделал счетчик таймаутов и добавление в unavailableNodes, если он становиться больше допустимого числа таймаутов, в остальных случаях добавляем ноду сразу в unavailableNodes. Удаление из unavailableNodes и очистку счетчиков таймаутов сделал автоматически через фиксированный интервал времени. Исправил на thread safety.

2022-10-16 11:26 UTC, LutsenkoDm commented
> Переделайте так, чтобы воркеры не блокировались проски запросами.

Вынес обработку проксируемых запросов в отдельный executor, описал в отчете что улучшилось.

2022-10-16 11:27 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/Stage3-report.md
> +заменив http протокол на другой, более эффективный, например, RPC или JSON-RPC. Также около 15% CPU уходит на метод
Да, json мне кажется в нашем случае избыточны, еще в прошлых коммитах убрал из отчета JSON-RPC.

2022-10-17 15:14 UTC, Fedoresko reviewed
В приннципе достатчно удобоваримо. Пока я б поставил 13/15. Но время вылизать код ещё есть. )

2022-10-17 15:14 UTC, Fedoresko commented on src/main/java/ok/dht/test/lutsenko/service/ProxyHandler.java
> +        );
В unavailableNodes моно ещё мапу сделать, и положить туда время, когда можно её удалять, то есть снова пробовтаь коннектиться. Но ладно, и так сойдет. )

2022-10-17 15:14 UTC, Fedoresko commented on src/main/java/ok/dht/test/lutsenko/service/ProxyHandler.java
> +        );
А втаком варианте по идее надо удалять из nodesTimeoutsNumberMap только те, которые были в unavailableNodes

2022-10-17 15:14 UTC, Fedoresko commented on src/main/java/ok/dht/test/lutsenko/service/ProxyHandler.java
> +                    case Request.METHOD_GET -> proceedGet(id, externalUrl);
Есть ощущение, что при проксировании можно как-то избавится от всей этой лапши, и не делать отдельные методы на все виды запросов. Это потом к тому же очень сложно поддерживать. Когда новые виды запросов будут добавляться, в 33 местах придется вносить изменения. Тут не помешал бы хороший рефакторинг )

2022-10-17 15:17 UTC, Fedoresko approved these changes

2022-10-18 12:42 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/Stage3-report.md
> +     273.663     0.775000        80424         4.44
Судя по профилю CPU, как раз 25% занимает C2, связано это с ним: первые запросы попадают в неоптимизированный код + сам C2 "отнимает" ресурсы пока работает.

2022-10-18 12:49 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/ProxyHandler.java
> +    private final ExecutorService proxyRequestExecutor = Executors.newFixedThreadPool(EXECUTOR_THREADS);
Оставил пока с отдельным executor, для меня так код более явный и с CompletableFuture мне кажется есть несколько нюансов: возможно не стоит смешивать в один экзекьютор отправку запросов и принятие, допустим все его воркеры будут ждать ответов, тогда запросы на отправку будут в очереди, что не есть хорошо, так отправка через sendAsync легче чем ожидание ответа. Также не очень понятно как обрабатывать ошибки и таймауты если использовать thenAccept. То есть если нода заболела, то при thenAccept мы бесконечно будем пытаться до нее достучаться.

2022-10-18 12:51 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/ProxyHandler.java
> +        );
Сделал из unavailableNodes мапу со временем, удаление из nodesTimeoutsNumberMap сделал когда счетчик переходит за допустимое значение таймаутов, то есть при добавлении в unavailableNodes.

2022-10-18 12:52 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/ProxyHandler.java
> +                    case Request.METHOD_GET -> proceedGet(id, externalUrl);
Отрефакторил, теперь проксирование "универсально".

2022-10-18 13:02 UTC, LutsenkoDm commented
> В приннципе достатчно удобоваримо. Пока я б поставил 13/15. Но время вылизать код ещё есть. )

Максимум баллов ведь должен быть удвоен так как я сделал еще в первую неделю, или баллы добавят уже когда будут проставлять их на портале?

2022-12-21 16:31 UTC, closed without merging