Yasevich Artem Stage4
polis-vk/2022-highload-dht pull request #101
Opened 2022-10-26 18:58 UTC by a-yasevich

Отчёт (снапшот после проверки) https://github.com/a-yasevich/2022-highload-dht/blob/a11598b06f307afaa05832d3eed45fb765786586/src/main/java/ok/dht/test/yasevich/profiling/stage4/report.md

2022-10-31 21:11 UTC, atimofeyev requested changes

2022-10-31 21:11 UTC, atimofeyev commented on src/main/java/ok/dht/test/yasevich/ReplicasManager.java
> +            return;
тут стоит вернуть ошибку

2022-10-31 21:11 UTC, atimofeyev commented on src/main/java/ok/dht/test/yasevich/ReplicasManager.java
> +            if (node.url.equals(selfUrl)) {
если первая нода в списке будет локальная то мы сделаем два запроса послдовательно, хотя хорошо было бы на все реплики, в том числе и в локальную идти параллельно

2022-10-31 21:11 UTC, atimofeyev commented on src/main/java/ok/dht/test/yasevich/ReplicasManager.java
> +        AtomicBoolean alreadyResponded = new AtomicBoolean();
в каждом методе много дублирования по работе с репликами (отправка запроса, ожидание ответа, проверка количества успешных/не успешных). Все это можно было бы реализовать один раз, а специфика обработчика (GET/PUT/DELETE) уже можно было бы передать как стратегию

2022-10-31 21:11 UTC, atimofeyev commented on src/main/java/ok/dht/test/yasevich/ServiceImpl.java
> +            workersPool.shutdown();
сначала стоит закрыть пул воркеров а потом сервер

2022-11-02 15:47 UTC, a-yasevich commented on src/main/java/ok/dht/test/yasevich/ReplicasManager.java
> +            if (node.url.equals(selfUrl)) {
Да, действительно) Исправил

2022-11-02 15:49 UTC, a-yasevich commented on src/main/java/ok/dht/test/yasevich/ReplicasManager.java
> +        AtomicBoolean alreadyResponded = new AtomicBoolean();
Порефакторил

2022-11-02 15:50 UTC, a-yasevich commented on src/main/java/ok/dht/test/yasevich/ServiceImpl.java
> +            workersPool.shutdown();
Исправил

2022-11-02 18:32 UTC, a-yasevich commented on src/main/java/ok/dht/test/yasevich/RandevouzHashingRouter.java
> +            if (counter.incrementAndGet() >= FAILED_REQUESTS_THRESHOLD) {
Да, понял, что идея не очень)

2022-11-04 07:03 UTC, atimofeyev requested changes

2022-11-04 07:04 UTC, atimofeyev approved these changes

2022-11-08 08:44 UTC, atimofeyev commented
15 баллов

2022-11-08 08:50 UTC, merged