Hw 3 sharding
polis-vk/2022-highload-dht pull request #107
Opened 2022-10-12 20:25 UTC by T-y-c-o-o-n

2022-10-17 19:35 UTC, Artyomcool commented
Разрезолвите пожалуйста конфликты

2022-10-17 19:44 UTC, Artyomcool requested changes

2022-10-17 19:44 UTC, Artyomcool commented on src/main/java/ok/dht/test/siniachenko/rendezvoushashing/NodeMapper.java
> +        // TODO: calculate node hashes one time
Таки да, согласен.

2022-10-17 19:44 UTC, Artyomcool commented on src/main/java/ok/dht/test/siniachenko/service/TycoonService.java
> +    public static final int THREAD_POOL_QUEUE_CAPACITY = (int) 1E20;
Повторяюсь ещё раз: не надо так делать.

2022-10-17 19:44 UTC, Artyomcool commented on src/main/java/ok/dht/test/siniachenko/service/TycoonService.java
> +                HttpResponse<byte[]> response = httpClient.send(
Если заблокировать одну ноду, посыпятся все.

2022-10-17 19:44 UTC, Artyomcool commented on src/main/java/ok/dht/test/siniachenko/service/TycoonService.java
> +    private Response upsert(String id, Request request) {
Многовато копипасты.

2022-10-18 19:37 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/service/TycoonService.java
> +    public static final int THREAD_POOL_QUEUE_CAPACITY = (int) 1E20;
исправил на 128

2022-10-19 06:54 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/rendezvoushashing/NodeMapper.java
> +        // TODO: calculate node hashes one time
улучшил хэш, позасылал рандомные ключи - они +- равномерно укладывались на нодах

2022-10-19 20:31 UTC, T-y-c-o-o-n commented on src/main/java/ok/dht/test/siniachenko/service/TycoonService.java
> +    private Response upsert(String id, Request request) {
Вынес копипасту
И наконец пофиксил то, что было отмечено в пулл ерквесте на 2 домашку - лишние нечитаемые лямбды. Сейчас код по мне читаемее - есть обработка запроса локальная, есть проксирование

2022-10-25 16:53 UTC, closed without merging