Stage 4 - Aleksandr Slastin ITMO
polis-vk/2022-highload-dht pull request #107
Opened 2022-10-26 19:22 UTC by aslastin

2022-12-27 14:20 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/slastin/SladkiiServer.java
> +        RequestHandler replicasRequestHandler = switch (request.getMethod()) {
Так же теперь на `SelectorThread` приходится слишком большая нагрузка, которую мы ещё во второй домашке пытались переложить на `ExecutorService`.

2022-12-27 14:20 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/slastin/reports/stage4/report.md
> +Кол-во аллокаций стало больше: на `7%` больше в `SelectorThread`, и на `7%` больше в `PayloadThread`. Это здесь естественно и связано с тем, что теперь каждый PUT запрос принимается 2 сторонами, а зн
А скрипты ты запускал сразу на всех нодах или только на той ноде, на которой велось профилирование?

2022-12-27 14:20 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/slastin/replication/ReplicasGetRequestHandler.java
> +        while (size != ack) {
спустя время я понял почему, но было бы не плохо написать это комментарием, как ты сделал это ниже.

2022-12-27 14:23 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/slastin/replication/ReplicasGetRequestHandler.java
> +        while (size != ack) {
хотя нет, осознал, что неправильно осознал, первый вопрос остаётся в силе.

2022-12-27 14:49 UTC, aslastin commented on src/main/java/ok/dht/test/slastin/SladkiiServer.java
> +    public void handleClientRequest(Request request, HttpSession session) throws IOException {
Потому что для моего функционала удобна реализация `handelRequest`, которая по умолчанию есть в `HttpServer`:
```java
public void handleRequest(Request request, HttpSession session) throws IOException {
        RequestHandler handler = findHandlerByHost(request); // сразу вернет отсюда null, потому что `mapperByHost` пустой
        if (handler == null) {
            handler = defaultMapper.find(request.getPath(), request.getMethod()); // выберется этот if
        }

        if (handler != null) { // в зависимости от пути выберет нужный обработчик
            handler.handleRequest(request, session);
        } else {
            handleDefault(request, session);
        }
    }
```

Здесь `defaultMapper` выберет какой надо обработчик в зависимости от`@Path`

В прошлой домашке у меня также был метод `handleRequestSelf` с аннотацией `@Path`, и я руками через Reflection извлекал `defaultMapper`, хотя в этом не было необходимости, учитывая, что необходимое для меня действие делает `HttpServer`.

2022-12-27 14:54 UTC, aslastin commented on src/main/java/ok/dht/test/slastin/sharding/ConsistentHashingManager.java
> +            if (!nodeIndices.contains(nodeIndex)) {
У меня также, но она здесь ошибается.

Пусть все vnodes расположены по кругу. Вызов `getNextVnodeIndex`вернет следующий vnodeIndex, который соответствует переданному ключу в этом круге. С каждой vnode ассоциирована нода, которую можно получить через `nodeIndexByVnodeIndex.get(vnodeIndex)`. Внутри цикла идем по кругу vnodes, увеличивая vnodeIndex, и добавляем только новые ноды.

Ну и если бы этот цикл не работал, то и тесты бы не проходились, потому что тогда бы никогда бы не вышли из цикла.

2022-12-27 14:58 UTC, aslastin commented on src/main/java/ok/dht/test/slastin/replication/ReplicasGetRequestHandler.java
> +                int currentAck = ackCounter.incrementAndGet();
Потому что `doAck` не принимает аргументов, однако внутри добавляю полученный `response`:

```java
Response response = sladkiiServer.processRequest(nodeIndex, id, request);
int status = response.getStatus();
if (status == HttpURLConnection.HTTP_OK || status == HttpURLConnection.HTTP_NOT_FOUND) {
    int currentAck = ackCounter.incrementAndGet();
    if (currentAck <= ack) {
        responses.offer(response); // вот здесь нужен доступ к response, которой бы не получил в doAck
    }
    if (currentAck == ack) {
        sladkiiServer.sendResponse(session, merge());
    }
} else {
    doFail();
}
```

2022-12-27 15:02 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/slastin/SladkiiServer.java
> +    public void handleClientRequest(Request request, HttpSession session) throws IOException {
На лекциях обсуждалось, что `@Path()` является не самым лучшим решением, и переопределение `handleRequest()` работает эффективнее. И когда до этого был переопределен `handleRequest()`, и его меняют на `@Path()`, то это выглядит как некая деградация.

2022-12-27 15:03 UTC, aslastin commented on src/main/java/ok/dht/test/slastin/replication/ReplicasGetRequestHandler.java
> +        while (size != ack) {
Да, смотри, попадаю в этот `merge` отсюда, из **1**:
```java
Response response = sladkiiServer.processRequest(nodeIndex, id, request);
int status = response.getStatus();
if (status == HttpURLConnection.HTTP_OK || status == HttpURLConnection.HTTP_NOT_FOUND) {
    int currentAck = ackCounter.incrementAndGet(); // 2
    if (currentAck <= ack) { 
        responses.offer(response); // 3
    }
    if (currentAck == ack) { // 1
        sladkiiServer.sendResponse(session, merge());
    }
} else {
    doFail();
}
```

Однако возможно исполнение, при котором потоки выполнили **2**, но еще не успели выполнить **3**, тем самым задача не будет добавлена в очередь. Если будет так, то во время обработки ответов внутри `getResultBuffer` внутри `responces` будут не все ответы, что не валидно, поэтому надо внутри потока, который будет мерджить ответы точно быть уверенным, что все другие потоки положили свои ответы, поэтому и происходит такая, немного кривая, проверка этого факта.

2022-12-27 15:10 UTC, aslastin commented on src/main/java/ok/dht/test/slastin/SladkiiServer.java
> +    public void handleClientRequest(Request request, HttpSession session) throws IOException {
В решении от преподавателей сейчас находится следующее:
``` java
@Override
public void handleRequest(Request request, HttpSession session) throws IOException {
    switch (request.getPath()) {
        case "/v0/entities" -> handleEntitiesRequest(request, session);
        case "/v0/entity" -> handleEntityRequest(request, session);
        default -> session.sendResponse(new Response(Response.BAD_REQUEST, Response.EMPTY));
    }
}
```

По факту, они делают тот же самый `getPath` и делают маппинг аналогичный `defaultMapper`.

Здесь они немного выигрывают, так как не надо делать генерацию обработчика через `addRequestHandlers` внутри `HttpServer`, однако обработчиков тут мало (всего 2, на каждый Path), и это происходит в самом начале, еще до старта сервера, поэтому не должно влиять на производительность.

2022-12-27 15:12 UTC, aslastin commented on src/main/java/ok/dht/test/slastin/replication/ReplicasGetRequestHandler.java
> +        return new Response(Response.OK, resultValue);
Не, здесь все ок, потому что этот бик извлек внутри `if` выше:
```java
if (resultBuffer == null || resultBuffer.get() == 0) { // вот тут
    return notFound();
}
```

2022-12-27 15:14 UTC, aslastin commented on src/main/java/ok/dht/test/slastin/SladkiiServer.java
> +                sendResponse(session, serviceUnavailable());
Вроде нет: если бы таска добавилась, то она была послала свой ответ, однако тут она не добавилась, отсюда выкидывается `RejectedExecutionException` и отправляется ответ на эту таску

2022-12-27 15:17 UTC, aslastin commented on src/main/java/ok/dht/test/slastin/SladkiiServer.java
> +        RequestHandler replicasRequestHandler = switch (request.getMethod()) {
Вот здесь создается `ReplicasRequestHandler`, у которого вызывается `handleRequest`:

```java
@Override
public void handleRequest(Request request, HttpSession session) throws IOException {
  this.request = request;
  this.session = session;

  before(); // не делаем ничего тяжелого, только в PUT/DELETE добавляем хедер в запрос

  for (int nodeIndex : sladkiiServer.getShardingManager().getNodeIndices(id, from)) {
      Runnable nodeTask = createNodeTask(nodeIndex); // создаем задачу, которая внутри себя ходит по сети / работает локально с БД
      if (!sladkiiServer.tryAddNodeTask(session, nodeIndex, nodeTask)) { // добавляем задачу на исполнение, чтобы ее выполнил `ExecutorService`
          doFail();
      }
  }
}
```

2022-12-27 15:20 UTC, aslastin commented on src/main/java/ok/dht/test/slastin/reports/stage4/report.md
> +Кол-во аллокаций стало больше: на `7%` больше в `SelectorThread`, и на `7%` больше в `PayloadThread`. Это здесь естественно и связано с тем, что теперь каждый PUT запрос принимается 2 сторонами, а зн
Профилирование велось на `Launch.java`, который внутри себя запускал все ноды. Поэтому профайлер собирал нагрузку одновременно со всех нод.

2022-12-27 20:16 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/slastin/sharding/ConsistentHashingManager.java
> +            if (!nodeIndices.contains(nodeIndex)) {
Нет, что тут происходит я понимаю: есть повторяющиеся ноды и т.д.
Суть в другом: ты используешь сет, в котором при добавлении уже имеющегося в нём элемента ничего не изменится. Поэтому бессмысленно заранее проверять, есть ли этот элемент в `nodeIndices` или нет.

2022-12-27 20:22 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/slastin/replication/ReplicasGetRequestHandler.java
> +                int currentAck = ackCounter.incrementAndGet();
``` java

public class ReplicasGetRequestHandler extends ReplicasRequestHandler {

    @Override
    protected void doAck() {
        super();
        if (currentAck <= ack) {
            responses.offer(response); // вот здесь нужен доступ к response, которой бы не получил в doAck
        }
    }

}
```

конечно не прям так, но думаю пошаманить и избавиться копипасты можно.

2022-12-27 20:25 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/slastin/replication/ReplicasGetRequestHandler.java
> +        while (size != ack) {
> спустя время я понял почему, но было бы не плохо написать это комментарием, как ты сделал это ниже.

Всё, верю. Здесь я о чём-то подобном задумался, но осознал, что в том случае всё норм.

2022-12-27 20:32 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/slastin/SladkiiServer.java
> +                sendResponse(session, serviceUnavailable());
Функция `tryAddNodeTask()` вызывается у тебя в двух местах. В одном случае и правда всё хорошо, а во-втором уже не очень.

2022-12-27 20:40 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/slastin/SladkiiServer.java
> +        RequestHandler replicasRequestHandler = switch (request.getMethod()) {
Во второй домашке мы пытались разгрузить `SelectorThread`, чтобы он занимался только принятием запросов от клиентов, а всю грязную работу выполняла рабочая лошадка `ExecutorService`. 
Здесь же `SelectorThread` начинает заниматься не тем, чем надо: он начинает лезть во внутреннюю логику сервиса, чего бы нам не очень и хотелось.
Если ты помнишь, то на лекции даже был спор о том, стоит ли валидировать айди в `SelectorThread` или производить валидацию в `ExecutorService`.

2022-12-27 20:46 UTC, aslastin commented on src/main/java/ok/dht/test/slastin/sharding/ConsistentHashingManager.java
> +            if (!nodeIndices.contains(nodeIndex)) {
И правда, видимо глаз замылился)

2023-01-08 22:24 UTC, aslastin commented on src/main/java/ok/dht/test/slastin/replication/ReplicasGetRequestHandler.java
> +                int currentAck = ackCounter.incrementAndGet();
Да, тут можно поиграться - в следущей таске избавился.

2023-01-08 22:30 UTC, aslastin commented on src/main/java/ok/dht/test/slastin/SladkiiServer.java
> +                sendResponse(session, serviceUnavailable());
Да, понял, что не так: если в процессе мерджинга какая-то из задач не добавится в пулл и вылелит с `RejectedExecutionException`, то отправится ответ клиенту. Но в то же время, ответ может отправиться и в результате мерджинга, поэтому кол-во ответов равно = #{`RejectedExecutionException`} + 1.

Фиксится если в случае `RejectedExecutionException` возвращать `false`.

И в следующей таске такой проблемы нет.

2023-01-09 10:59 UTC, Mr-Ravil approved these changes
13 баллов.

2023-01-09 11:00 UTC, Mr-Ravil requested changes
необходимо разрешить конфликты.

2023-01-09 14:55 UTC, Mr-Ravil approved these changes

2023-01-09 14:55 UTC, merged