Add stage 1
polis-vk/2022-highload-dht pull request #11
Opened 2022-09-24 19:54 UTC by LutsenkoDm

2022-09-26 19:39 UTC, pashchenko8 requested changes

2022-09-26 19:39 UTC, pashchenko8 commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +Подробные результаты нагрузочного тестирования находятся в папке /reports/wrk
1 - все картинки вставляйте сюда
2 - не нужно wrk скринить, можно просто вставить вывод

2022-09-26 19:39 UTC, pashchenko8 commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +
совершенно ничего нету про персентили

2022-09-26 19:39 UTC, pashchenko8 commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +    94.98% отводится на выполнение метода get в dao
в хитмапе вы выделили в том числе и с2 ..... было ли это осознано и надо ли учитывать С2 в анализе?

2022-09-26 19:39 UTC, pashchenko8 commented on src/main/java/ok/dht/test/lutsenko/DemoService.java
> +    private final Set<HttpSession> sessions = new HashSet<>();
и вообще посмотрите внуть HttpServer кажется что где-то уже должны же храниться соединения

2022-09-26 20:09 UTC, pashchenko8 commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +    Возможная оптимизация - использование dao, не требующее переводов массивов строк в байты.
тут возможно я не прав, анализ всего кода это хорошо, но все-же тип хранения данных это про прошлый семестр

2022-09-27 12:59 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/dao/DaoUtils2.java
> +public final class DaoUtils2 {
Переименовал в StringUtils, в 1 файл не помещается из-за ограничения на число строк

2022-09-27 13:00 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/DemoService.java
> +                sessions.add(session);
Переделал без использования Set

2022-09-27 13:00 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/DemoService.java
> +            Files.createTempDirectory("service");
Исправил

2022-09-27 13:00 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/DemoService.java
> +        sessions.clear();
Переделал без использования Set

2022-09-27 13:01 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/DemoService.java
> +        server.addRequestHandlers(this);
Перенес до вызова start

2022-09-27 13:04 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +Размер таблицы в памяти dao равен 1 МБ
Имеется в виду параметр flushThresholdBytes, то есть ограничение на суммарный размер элементов в MemTable, после достижения которого будет запущен flush и выполнена очистка MemTable (после её записи на диск)

2022-09-27 13:05 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +    Среднее время обработки запроса составляет 0.96 ms, максимальное - 27.04 ms
Вынес это в другое место

2022-09-27 13:05 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +    Из результатов профилирования следует, что обработка запроса (one.nio.net.Session.process) занимает 72.46%
Дополнил

2022-09-27 13:06 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +    Таким образом, разница между средним и максимальным временем объясняется тем, что сервер не успевает
Не очень корректно написал, имелось в виду что большая часть времени уходит на работу с сетью а не с dao. В отчете переформулировал этот момент

2022-09-27 13:09 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +    Единственное решение для увеличения производительности в данном случае - сделать сервер асинхронным.
Убрал это предложение, скорее имел в виду многопоточным

2022-09-27 13:12 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +
Добавил в отчет

2022-09-27 13:12 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +    94.98% отводится на выполнение метода get в dao
Скорее неосознанно, не стоит

2022-09-27 13:14 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/DemoService.java
> +    private final Set<HttpSession> sessions = new HashSet<>();
Переделал без Set

2022-09-28 11:58 UTC, pashchenko8 requested changes

2022-09-28 11:58 UTC, pashchenko8 commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +В 90% случаев время запроса не превышает 1.18ms, а в 99% - 6.00ms, что можно считать стабильной нагрузкой.
что значит "можно считать стабильной нагрузкой"?

2022-09-28 11:58 UTC, pashchenko8 commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +    Остальное время отводится на native код, в основном: one.nio.net.NativeSelector.epollWait - 12.55%.
что делает этот код?

2022-09-28 11:58 UTC, pashchenko8 commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +    15.57% на сам метод handlePut из DemoService
на что конкретно?

2022-09-28 11:58 UTC, pashchenko8 commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +    Остальное - для обработки запроса с помощью one.nio - более 60% аллокаций.
на что?

2022-09-28 11:58 UTC, pashchenko8 commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +    процессорного времени, из которых 26.7% - выполнение метода get в dao, где большая часть времени уходит
get работает дольше чем put, при этом скорость тут лучше.... почему?

2022-09-28 18:13 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +В 90% случаев время запроса не превышает 1.18ms, а в 99% - 6.00ms, что можно считать стабильной нагрузкой.
Мне кажется однозначного ответа на данный вопрос нет, я ориентировался на то, что было сказано на лекции: сервер не должен захлебываться и время запросов не должно быть равно сотням миллисекунд или секундам, нормальные значения: около 1 ms или несколько миллисекунд.

2022-09-28 18:13 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +    15.57% на сам метод handlePut из DemoService
На перевод вставляемого value в строку

2022-09-28 18:14 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +    процессорного времени, из которых 26.7% - выполнение метода get в dao, где большая часть времени уходит
Связано с тем что rate в случае put запросов был 5000 в секунду. а при get запросах 2500.

2022-09-28 18:34 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/report.md
> +    процессорного времени, из которых 26.7% - выполнение метода get в dao, где большая часть времени уходит
Rate для get запросов был выбран ниже,  если выбрать его таким как и при put запросах, то время выполнения одного get запроса будет не совсем адекватным.

2022-10-06 12:20 UTC, pashchenko8 commented
8 баллов

2022-10-06 12:20 UTC, pashchenko8 approved these changes
8 баллов

2022-12-21 16:31 UTC, closed without merging