Stage 5 Shestakova Alina
polis-vk/2022-highload-dht pull request #130
Opened 2022-11-01 23:29 UTC by Anilochka

Отчёт: https://github.com/Anilochka/2022-highload-dht-1/blob/stage5/src/main/java/ok/dht/test/shestakova/report/res/stage-5_report.md

2022-11-16 20:48 UTC, atimofeyev requested changes

2022-11-16 20:48 UTC, atimofeyev commented on src/main/java/ok/dht/test/pashchenko/MyServer.java
> +                        LOG.error("executor sendResponse", e);
отправку респонса можно было бы вынести в один метод, и передавать пару параметров, неплохо бы сократилось количество кода

2022-11-17 19:07 UTC, Anilochka commented on src/main/java/ok/dht/test/pashchenko/MyServer.java
> +        AtomicInteger successAtomic = new AtomicInteger();
прошу прощения, почему-то возник конфликт с главной веткой, и этот файл ([src/main/java/ok/dht/test/pashchenko/MyServer.java](https://github.com/polis-vk/2022-highload-dht/pull/130/files/58c20affdc2642a6c17f64622ef94503affd3093#diff-e849a472a4270169ccdda213266d71aba95b927ffbd722b5528ad662150ddb4e)) - не мой, а лекторов, - попал ко мне в PR
теперь разрешила конфликты, его больше тут нет

2022-11-17 19:08 UTC, Anilochka commented on src/main/java/ok/dht/test/pashchenko/MyServer.java
> +            session.sendResponse(new Response(Response.BAD_REQUEST, Response.EMPTY));
разрешила конфликты, этого файла с лекций больше нет

2022-11-17 19:08 UTC, Anilochka commented on src/main/java/ok/dht/test/pashchenko/MyServer.java
> +                        LOG.error("executor sendResponse", e);
разрешила конфликты, этого файла с лекций больше нет

2022-11-19 20:26 UTC, atimofeyev requested changes

2022-11-19 20:26 UTC, atimofeyev commented on src/main/java/ok/dht/test/shestakova/DemoHttpServer.java
> +        if (request.getHeader("internal") != null || request.getPath().contains("/service/message")) {
в этом случае зря определяли targetNodes, к тому же в потоке селектора

2022-11-19 20:26 UTC, atimofeyev commented on src/main/java/ok/dht/test/shestakova/DemoHttpServer.java
> +                Response response = handleInternalRequest(request, session);
локальный вызов будет делаться не параллельно другим, хорошо бы его так же делать асинхронно

2022-11-19 20:26 UTC, atimofeyev commented on src/main/java/ok/dht/test/shestakova/DemoHttpServer.java
> +                if (successCount.decrementAndGet() == 0) {
а почему success, тут может юыть и не success

2022-11-19 20:26 UTC, atimofeyev commented on src/main/java/ok/dht/test/shestakova/DemoHttpServer.java
> +    private void sendAsync(CompletableFuture<List<Response>> resultFuture, List<Response> responses,
вот такая схема когда в параметрах передаются мутабельные поля - очень сложная. Лучше ее избегать, аттрибуты - иммутабельные, результат возвращаем в ответе

2022-11-21 21:47 UTC, Anilochka commented on src/main/java/ok/dht/test/shestakova/DemoHttpServer.java
> +        if (request.getHeader("internal") != null || request.getPath().contains("/service/message")) {
исправила

2022-11-21 21:47 UTC, Anilochka commented on src/main/java/ok/dht/test/shestakova/DemoHttpServer.java
> +                Response response = handleInternalRequest(request, session);
поправила

2022-11-21 21:48 UTC, Anilochka commented on src/main/java/ok/dht/test/shestakova/DemoHttpServer.java
> +                if (successCount.decrementAndGet() == 0) {
добавила проверку на получаемый response, теперь рассматривается случай не success

2022-11-21 21:52 UTC, Anilochka commented on src/main/java/ok/dht/test/shestakova/DemoHttpServer.java
> +    private void sendAsync(CompletableFuture<List<Response>> resultFuture, List<Response> responses,
поправила (изначально отправка запроса не была выделена в этот отдельный метод с мутабельными полями, но кодклимат ругался на сложность кода, поэтому так неудачно его вынесла)

2022-11-26 20:27 UTC, atimofeyev requested changes

2022-11-26 20:27 UTC, atimofeyev commented on src/main/java/ok/dht/test/shestakova/DemoHttpServer.java
> +        return responseCompletableFuture.get();
у нас тут получается все выполняется последовательно

2022-11-26 22:04 UTC, Anilochka commented on src/main/java/ok/dht/test/shestakova/DemoHttpServer.java
> +        return responseCompletableFuture.get();
поправила

2022-12-03 19:10 UTC, atimofeyev approved these changes
15 баллов

2022-12-08 12:37 UTC, merged