Stage 3 tests for checking distribution quality Shestakova Alina
polis-vk/2022-highload-dht pull request #14
Opened 2022-10-20 18:01 UTC by Anilochka

2022-10-26 21:06 UTC, AdvancerMan commented on src/test/java/ok/dht/ShardingTest.java
> +            serviceInfos.get(0).upsert(key, value);
Считаю, что стоит добавить ack=1, from=1, чтобы данные отправлялись только на один шард

2022-10-26 21:07 UTC, AdvancerMan commented on src/test/java/ok/dht/ShardingTest.java
> +            }
Считаю, что стоит сделать `avgEntriesCountPerNode = keysCount / serviceInfos.size()`. Если какие-то данные не сохранились, то произошла ошибка и тесты должны упасть

2022-10-27 22:06 UTC, Anilochka commented on src/test/java/ok/dht/ShardingTest.java
> +            serviceInfos.get(0).upsert(key, value);
Согласна, этот PR долго не мог принять новые реалии с появлением репликации..)

2022-10-27 22:07 UTC, Anilochka commented on src/test/java/ok/dht/ShardingTest.java
> +            }
Да, точно, сравнение с эталонным значением тут уместнее, согласна, спасибо!

2022-11-26 14:05 UTC, Artyomcool approved these changes
4 доп. балла

2022-11-30 10:56 UTC, incubos requested changes
Тесты не проходят.

2022-12-20 15:51 UTC, closed without merging