Stage 1 Kirill Kurdyukov
polis-vk/2022-highload-dht pull request #14
Opened 2022-09-24 22:44 UTC by KirillKurdyukov

Version 1

2022-09-27 18:38 UTC, GaDiss commented
Не хватает хитмапов в профайлере.

2022-09-27 19:16 UTC, GaDiss commented on src/main/java/ok/dht/test/kurdyukov/report-stage-1.md
> +что вызвано  особенностью нашей бд.
Опечатки в отчёте не радуют глаз. 

Насчёт вывода: Про какую особенность бд идёт речь? Как это можно оптимизировать?

2022-09-27 19:16 UTC, GaDiss commented on src/main/java/ok/dht/test/kurdyukov/report-stage-1.md
> +
Можно сделать больше выводов: Какие есть слабости в используемой БД и как их можно улучшить? Также хочется видеть больше анализа в отчёте, а не голые цифры запуска wrk2.

2022-10-04 12:47 UTC, GaDiss requested changes
Есть небольшие замечания

2022-10-06 17:11 UTC, KirillKurdyukov commented
Поправил спецификацию. После дедлайна вмержили тест. Поправил обработку

2022-10-12 14:09 UTC, GaDiss approved these changes
Понравилось, что есть идеи по оптимизации. Но многие моменты в отчёте не объяснены, 10 баллов

2022-10-12 14:09 UTC, GaDiss commented on src/main/java/ok/dht/test/kurdyukov/report-stage-1.md
> +   6000 rate - сервер отвечал стабильно не захлебывался, в среднем время ответа 1.54ms, max - 43.10ms.
Нужно явно объяснять, почему есть разница почти в 30 раз между средним и самым долгим ответов.

2022-10-13 12:27 UTC, merged