Stage 5 - Aleksandr Slastin ITMO
polis-vk/2022-highload-dht pull request #153
Opened 2022-11-09 20:45 UTC by aslastin

2023-01-08 22:36 UTC, aslastin commented
Без бонуса

2023-01-09 10:58 UTC, Mr-Ravil approved these changes
14 баллов.

2023-01-09 11:00 UTC, Mr-Ravil requested changes
необходимо разрешить конфликты

2023-01-09 14:29 UTC, aslastin commented on src/main/java/ok/dht/test/slastin/replication/ReplicasRequestHandler.java
> +                    futureResponse.cancel(true);
Да, правда - можно добавить такую же функцию отмены и в случае, когда отправляем ответ `notEnoughReplicas()`

2023-01-10 20:30 UTC, Mr-Ravil approved these changes

2023-01-10 20:30 UTC, merged