Stage 5 Kuleshov Egor ITMO
polis-vk/2022-highload-dht pull request #156
Opened 2022-11-10 06:20 UTC by Kuleshovegor

2023-01-10 10:56 UTC, Mr-Ravil requested changes
Изменения должны касаться лишь своей папки.
Необходимо разрешить конфликты.

2023-01-10 11:50 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/kuleshov/Service.java
> +        if (!isCorrectId(id)) {
Почему здесь есть проверка `id` на корректность, а в других запросах нет?
Зачем здесь вообще ещё одна проверка, если проверка уже проводилась в `handleRequest()`? И почему здесь проверка проводится через валидатор, а в `handleRequest()` в ручную?

2023-01-10 11:50 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/kuleshov/SlaveResponseHandler.java
> +                    if (handleAck(new Response(Response.CREATED, Response.EMPTY))) {
Почему здесь результат `handleAck()` используется, а в остальных нет? Да и зачем здесь `return`, когда наборолось ровно `ack` успехов?

2023-01-10 11:50 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/kuleshov/SlaveResponseHandler.java
> +            sendResponse(response);
Зачем каждый раз генерировать новый `responce` для `hanldeAck()`, если он будет использоваться только тогда, когда мы набрали ровно `ack` успехов? Почему бы не создавать `responce` лишь в тот момент, когда он нам пригодится, тем самым избавившись от лишних аллокаций?

2023-01-10 11:50 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/kuleshov/report/stage5/report.md
> +Latency     2.94s     1.54s    8.03s    72.71%
здесь же явно видно, что `PUT` при `rps = 10к` захлёбывается.

2023-01-10 11:50 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/kuleshov/report/stage5/report.md
> +```
А где для `GET`?

2023-01-10 11:50 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/kuleshov/report/stage5/report.md
> +Transfer/sec:    138.06KB
какой скрипт здесь запускался?

2023-01-10 11:50 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/kuleshov/report/stage5/report.md
> +Transfer/sec:    137.42KB
и здесь?

2023-01-10 11:50 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/kuleshov/report/stage5/report.md
> +физической машине.
А где профилирование?

2023-01-11 20:01 UTC, Kuleshovegor commented on src/main/java/ok/dht/test/kuleshov/Service.java
> +        if (!isCorrectId(id)) {
Изначально логика работы с ```id``` и данными была расположена в ```Service```, но далее, чтобы пересылать запросы на другие ноды, в ```CoolAsyncHttpServer::handleRequest()``` потребовалось также работать с ```id```, поэтому там тоже появилась проверка, чтобы сразу отсекать плохие запросы. Таким образом появилось 2 проверки. Сейчас действительно проверка в ```Service``` лишняя. Убрал её, исправил.

2023-01-11 20:02 UTC, Kuleshovegor commented on src/main/java/ok/dht/test/kuleshov/SlaveResponseHandler.java
> +                    if (handleAck(new Response(Response.CREATED, Response.EMPTY))) {
По начальной задумке при возвращении ```true``` должен был отправляться response клиенту, но почему-то я потом решил оправлять ответ внутри ```handleAck()```, что вызвало еще и лишние аллокации. Исправил.

2023-01-11 20:02 UTC, Kuleshovegor commented on src/main/java/ok/dht/test/kuleshov/SlaveResponseHandler.java
> +            sendResponse(response);
Действительно генерировать не нужно, я поэтому и возвращал ```true``` и ```false```, чтобы потом отправлять ответ, но в какой-то момент свернул не туда и решил отправлять внутри ```handleAck()```. Исправил.

2023-01-13 19:17 UTC, Mr-Ravil approved these changes
10 баллов.

2023-01-13 19:25 UTC, merged