Add `start > end` test for Stage 6
polis-vk/2022-highload-dht pull request #160
Opened 2022-11-13 19:39 UTC by AdvancerMan

Тест запускается на рендже `["1", "0")`, что невалидно, так как `"1" > "0"`, поэтому ожидаю код ответа 400.

2022-11-26 14:53 UTC, AdvancerMan commented
Тест не проходил на референсной реализации, написанной на лекции. Пофиксил в последнем (на момент написания комментария) коммите.

2022-11-27 18:06 UTC, Artyomcool approved these changes
3 балла

2022-11-30 09:49 UTC, incubos requested changes
Новый тест не проходит. Видимо, нужно поправить reference?

2022-11-30 20:01 UTC, AdvancerMan commented
На референсной реализации тест работает. Зависает на реализации из `ok.dht.test.galeev`. Нужно ли чинить?

2022-12-01 09:01 UTC, incubos commented
Не будем чинить. Баллы проставлены.

2022-12-01 09:01 UTC, closed without merging