Stage6 Lutsenko Dmiitrii
polis-vk/2022-highload-dht pull request #169
Opened 2022-11-15 17:37 UTC by LutsenkoDm

2022-11-26 21:15 UTC, atimofeyev requested changes

2022-11-26 21:15 UTC, atimofeyev commented on src/main/java/ok/dht/test/lutsenko/service/DemoService.java
> +                    ? CompletableFuture.completedFuture(daoHandler.proceed(id, request, requestTime))
ну здесь мы выполняем все последовательно, а по адумке должны параллельно

2022-11-26 21:15 UTC, atimofeyev commented on src/main/java/ok/dht/test/lutsenko/service/ExtendedSession.java
> +        server.incRequestsProcessed();
а для чего тут переопределен метод?

2022-11-28 12:02 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/DemoService.java
> +        Set<Integer> replicaNodesPositions = new HashSet<>(from);
Заменил на 2 * from

2022-11-28 12:11 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/DemoService.java
> +                    ? CompletableFuture.completedFuture(daoHandler.proceed(id, request, requestTime))
Дело в том, что в прошлом stage выполнял нагрузочное тестирование с обеими вариантами для dao, как сейчас и через supplyAsync и оказалось что  supplyAsync  проигрывает примерно на 5-7% в производительности когда данные у нас читаются из page кэша или из памяти, и даже при честном чтении с диска показатели были примерно равны, поэтому сделал через completedFuture. И на лекции говорилось, что наше dao отвечает быстро, опять же в идеале данные берутся из кэша. Тут мне кажется будет tradeoff в контексте того, что если все работает хорошо и быстро, то supplyAsync  медленнее из-за смены контекста, но если что-то будет не так, например диск начнет "болеть", то с синхронным выполнением будет неприятно, поэтому заменил все же на async, так как это более общий случай, но с другой стороны если dao будет медленно отвечать, то рано или поздно вся данная реплика будет помечена как unavalable

2022-12-17 17:09 UTC, atimofeyev commented on src/main/java/ok/dht/test/lutsenko/service/RangeRequestHandler.java
> +                if (byteBuffer.remaining() < entryChunk.sizeForBuffer) {
текущая логика тоже ускользает от меня, можете тут немного прокомментировать словами?

2022-12-20 16:39 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/RangeRequestHandler.java
> +                if (byteBuffer.remaining() < entryChunk.sizeForBuffer) {
Каждая entry является одним чанком, чтобы не экранировать символы
size - размер key и value для чанка
sizeForBuffer - сколько байт готовый чанк занимает в буфере
Складываем в буфер чанки и пишем в сокет такие буфера из пачек чанков
Также в буфере всегда зарезервировано место под последний, завершающий чанк, что сэкономит 1 syscall
с помощью limit, соответственно вызов remaining учитывает этот limit)
Если можем поместить новый чанк в буфер, то просто добавляем в него и идем дальше
Если места не хватает, то пишем буфер в сокет и добавляем текущую entry, которая не поместилась:
если ее sizeForBuffer больше размера буфера, то есть она не влезает даже в пустой буфер, то
алоцируем буфер размером sizeForBuffer (экономим syscall-ы) + место для последнего чанка и ставим лимит до него.  Можно делать и wrap, но не зная характер и структуру данных нельзя сказать что лучше, 
если entry размером больше буфера мало относительно числа тех, что меньше, то wrap, иначе allocate.

2022-12-20 17:39 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/RangeRequestHandler.java
> +                if (byteBuffer.remaining() < entryChunk.sizeForBuffer) {
Была проблема, что если в сокет не все из буфера записалось, то оно терялось. Исправил, запоминая последний чанк для entry, полученной из next, и на следующем вызове write пишем в сокет, то что не записалось на предыдущем write, когда все записали в сокет, то старый буфер очищается и добавляется entryChunck, который запомнили.

2022-12-20 17:47 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/RangeRequestHandler.java
> +                if (byteBuffer.remaining() < entryChunk.sizeForBuffer) {
Когда entryChunck когда уже  не помещается в буфер, то буфер пытаемся записать в сокет, если записали не полностью, то прочитанный entryChunck надо запомнить, потому что в буфер мы его не поместили, соответственно на следующем вызове write дописываем старый недописанный буфер в сокет и только после полной записи в сокет очищаем буфер и кладем в него чанк, который в самом начале не влез в буфер при том, что буфер сразу в сокет не получилось записать

2022-12-26 15:30 UTC, atimofeyev requested changes

2022-12-26 15:30 UTC, atimofeyev commented on src/main/java/ok/dht/test/lutsenko/service/ExtendedSession.java
> +                super.server.handleRequest(handling, this);
а зачем переопределять этот метод, и копипастить, если можно было отправить свой QueueItem через write()?

2022-12-26 15:30 UTC, atimofeyev commented on src/main/java/ok/dht/test/lutsenko/service/RangeRequestHandler.java
> +                    return written;
не понимаю как мы тут гарантируем то что отдаем весь рейндж, вот случился тут ретурн, когда мы продолжим итерироdаться и писать в сокет?

2022-12-26 16:14 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/RangeRequestHandler.java
> +                    return written;
1) sendQueueItem был создан как аналог sendResponse, с одним лишь отличием, что вместо Response тут queueItem, поэтому и был сделан копипаст, чтобы можно было легко понять что это 2 одинаковых по сути метода и читающему не задумываться о специфике с queueItem.  super.server.handleRequest(handling, this) вроде нельзя заменить на  write так как он вызывается после после handling = pipeline.pollFirst() и там может быть уже не range запрос, а обычный в pipeline.pollFirst(). 

2) Продолжим при повторных вызовах этого write, remaining ведь будет не 0, следовательно write вызовется еще раз пока не вычитаем весь буфер. В ситуации если останется только peekedEntryChunk, отправим и ее, так как в writeAgain пишем в буфер,  следовательно remaining будет не 0 пока не отправим эту последнюю entry.

2022-12-27 07:38 UTC, atimofeyev commented on src/main/java/ok/dht/test/lutsenko/service/RangeRequestHandler.java
> +                    return written;
1. я не про переопределение handleRequest(), а про переопределение sendResponse().
Это не два одинаковых по сути метода, в сессии уже есть два разных метода, один - sendResponse, которые принимает в параметрах респонс, а второй  write() который принимает QueueItem.
sendResponse по семантике такой что отправляет короткий ответи и сразе же смотрит а есть ли еще что-то обработать.
В нашем случае надо отправить жирный ответ, не обязателньо что сразу весь конечно, но сильно убежден что не стоит его загонять в семантику sendResponse и пытаться как-то указать что это тоже самое

2. повторные вызовы write уже будут делаться в потоках селектора и мы будем итерироваться по базе в селектор потоках, тоже такое себе

2022-12-27 10:54 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/RangeRequestHandler.java
> +                    return written;
В sendQueueItem оставил только write и  super.server.incRequestsProcessed() с this.handling = pipeline.pollFirst(), так как без pollFirst работать не будет. Данный метод был сделан чтобы избавиться от instanseOf если бы переопределялся метод writeResponse, так как в результате writeResponse все равно бы вызывался внутри sendResponse, я подумал почему бы не сделать так сразу - более кратко, ведь Response нам не нужен.

2022-12-27 10:57 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/RangeRequestHandler.java
> +                    return written;
Сделал переопределение (копипаст с небольшими изменениями) processWrite с пулом потоков + добавил профилирование подтверждающее, что в селектор тредах теперь write не вызывается (Файл range_10000_entries_updated_cpu.html)

2022-12-27 17:49 UTC, atimofeyev requested changes

2022-12-27 17:49 UTC, atimofeyev commented on src/main/java/ok/dht/test/lutsenko/service/ExtendedSession.java
> +        executor.execute(() -> {
не очень решение, тут мы будем брать не только рейндж айтемы но и обычные айтемы которые пишутся от обычных запросов

2022-12-27 17:51 UTC, atimofeyev commented on src/main/java/ok/dht/test/lutsenko/service/ExtendedSession.java
> +        executor.execute(() -> {
ну и как следсвие я думаю можно сделать такой тест, в результате которого мы будем из базы читать все равно из селектор потоков, в данном случае вы просто его разделяете с новым пулом

2022-12-27 18:52 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/ExtendedSession.java
> +        executor.execute(() -> {
Добавил проверку на range item-ы, теперь в executor уходят только они, обычные обрабатываются как раньше.

2022-12-29 10:08 UTC, atimofeyev approved these changes
Предлагаю остановиться на текущем решении, и готов дать 12 баллов за него.

поясню почему не 15, задача вроде бы решена но какие минусы:
- много копипаста, убежден что можно сделать без лишних переопределений
- дополнительный пул потоков, который может быть перегружен, и не успевать отдавать рейндж ответы, при этом пул воркеров будет курить

2022-12-29 10:33 UTC, LutsenkoDm commented
> Предлагаю остановиться на текущем решении, и готов дать 12 баллов за него.
> 
> поясню почему не 15, задача вроде бы решена но какие минусы:
> 
> * много копипаста, убежден что можно сделать без лишних переопределений
> * дополнительный пул потоков, который может быть перегружен, и не успевать отдавать рейндж ответы, при этом пул воркеров будет курить

Согласен

2022-12-29 12:25 UTC, merged