add solutio
polis-vk/2022-highload-dht pull request #19
Opened 2022-09-25 20:05 UTC by mk17ru

2022-10-04 12:50 UTC, GaDiss requested changes
В PR с решением нужно менять только файлы в своей папке (frolovm), содержимое папки drozdov менять не стоит.
В отчёте хочется видеть более детальный анализ полученных значений и больше гипотез/предположений по оптимизации DB

2022-10-04 18:31 UTC, mk17ru commented on src/main/java/ok/dht/test/frolovm/ServiceImpl.java
> +        server.addRequestHandlers(this);
Пофиксил

2022-10-04 18:31 UTC, mk17ru commented on src/main/java/ok/dht/test/frolovm/ServiceImpl.java
> +    private static final byte[] NO_SUCH_METHOD = Utf8.toBytes("No such method.");
Пофиксил

2022-10-04 18:45 UTC, mk17ru commented on src/main/java/ok/dht/test/frolovm/report-documents/report.md
> +Основная часть времени CPU при работе с ServiceImpl приходится на метод ConcurrentSkipListMap.put(~3% от общего CPU), который в свою очередь
Видимо некорректно выразился. Я имел ввиду, что в данном домашнем задании мы реализуем service, и стоит рассмотреть возможность улучшения его производительности, поэтому рассмотрел в отдельности его. Конечно его доля CPU невелика всего 3% от общего. Но основная нагрузка приходится на сторонние библиотеки, которые трудно как-то улучшить в рамках дз. (Формулировку исправил)

2022-10-09 16:45 UTC, mk17ru commented on src/main/java/ok/dht/test/frolovm/report-documents/report.md
> +Service аллоцирует ~25%.
Про сервис написал ниже, что Flush in bd на 10k занимает 2.79%, а при 15k ~25%, а при 20k ~10%. Что связано с увеличением размера и количества данных и тем, успевает
ли сервер и база данных обрабатывать запросы.
В сети основная аллокация(65%) приходится на processRead, который в основном тратит ресурсы на создание. массивов byte[] или создание String. Это можно улучшить убрав лишние конвертации из массивов byte[] в String и обратно.
Также стоит упомянуть, что на работу с Selectors тратится примерно 10% памяти, это уже кишки one.nio, но какую-то часть лишних аллокаций можно избежать, если запросы успевают исполняться и не накапливаются в очереди.

2022-10-09 17:06 UTC, mk17ru commented on src/main/java/ok/dht/test/frolovm/report-documents/report.md
> +Основное время тратится на getOffset из jdk.incubator.foreign.MemoryAccess и Comparator compare в entryIndex.
"Большую часть CPU 93% работа с базой данных(MemorySegmentDao). 
Обработка request занимает 2%. Selectors - 2%. Garbage Collector - 2%" - работа с сетью стала меньшей, потому что Get запрос обычно легче, нам не приходиться парсить данные которые нам приходят, а также он идемпотентный, а значит можно использовать различные оптимизации. Также get запрос в базу медленнее, потому что наша база lsm, а значит она отдает приоритет производительности операций записи, взамен производительности операций чтения.
getOffset из jdk.incubator.foreign.MemoryAccess - это по сути метод чтения информации из базы, также мы вызываем его при поиске бинпоиском индекса нашей сущности. 
Comparator compare в entryIndex - используется в том же бинпоиске при поиске сущности.

2022-10-09 17:37 UTC, mk17ru commented on src/main/java/ok/dht/test/frolovm/report-documents/report.md
> +Когда сервер захлебывается резкий рост Latency проиcходит сразу со старта: графики (put20000, get8000).
При увеличении нагрузки на сервер настолько, что он перестает справляться с кол-вом запросов или работает на пределе своих возможностей -  понятно, что задержка ответа будет расти.
При увеличении нагрузки запросы начинают скапливаться в очереди и соответсвенно время ответа увеличивается, также при увеличении кол-ва запросов увеличивается выделения ресурсов, из-за чего увеличивается вероятность прихода Garbage collectors, время его работы и его процент CPU сервера.

Подводя итоги узкими местами сервиса я бы назвал:
1. Поиск значения в базе данных при Get запросах
2. Работа с сетью 
3. Преобразования из byte[] в String и обратно
4. Запросы начинают медленно обрабатываться когда происходит flush in bd  
5. Во время работы garbage collectors ухудшается производительность
6. Также большое время занимает работа с MemorySegment, однако данное решение достаточно эффективное и его большой процент в CPU и ALLOC связан с простотой запросов к серверу(т.е основная работа приходится как раз на поиске или записи MemorySegment).

2022-10-12 14:22 UTC, GaDiss commented
На комментарии ответил поздновато, но качественно.

2022-10-12 14:29 UTC, GaDiss approved these changes
14 баллов

2022-10-13 12:40 UTC, merged

2022-10-13 17:25 UTC, GaDiss reviewed
15 баллов