Stage1 AlexeyShik
polis-vk/2022-highload-dht pull request #22
Opened 2022-09-26 14:35 UTC by AlexeyShik

2022-09-28 15:20 UTC, AlexeyShik commented
Если присмотреться, то скринах работы wrk для put запросов у меня будут разные названия скриптов. На самом деле там был один и тот же скрипт, просто сначала я использовал его для искусственного наполнения бд, поэтому назвал fill_database, потом назвал post_query_different_keys, потом решил укоротить до post_query, а потом вспомнил, что у нас put запросы и назвал put_query. Некрасиво вышло, но перезапускать ради одинакового названия не хочется.

2022-09-28 15:24 UTC, AlexeyShik commented
А еще у меня нет хитмапы, потому что async-profiler из ветки Артема не завелся за достаточно быстрое время, и мною было принято решение использовать текущий мастер. В целом это и не было обязательным условием для текущего задания. В следующих дз попробую снова втащить хитмапу.

2022-09-30 18:25 UTC, AlexeyShik commented
upd: втащил в проект хитмапу, в следующих домашках будет)

2022-10-04 12:52 UTC, GaDiss requested changes
Вывод можно дополнить. Например, можешь посмотреть на процентили latency. В остальном всё ок

2022-10-06 19:58 UTC, AlexeyShik commented on src/main/java/ok/dht/test/shik/ServiceImpl.java
> +        server.addRequestHandlers(this);
fixed

2022-10-13 17:12 UTC, AlexeyShik commented on src/main/java/ok/dht/test/shik/profiler_reports/profiler_result.md
> +* Даже при большой загрузке бд запись в нее остается очень быстрой
Сорри, пропустил, что на комментарии обязательно надо отвечать. 
Можно добавить, что фоновый compaction поток берет глобальную блокировку при флаше таблиц с уровня i на i+1, это объясняет замедление 99-99,9% персентиля. Я это заметил в дз2 и там подробнее описал, каким образом можно уменьшить расход на блокировки.
А еще в LevelDB маловато кэшей. Можно сделать кэш для часто читающихся записей, то есть похранить их в отдельной in-memory табличке. 
Также можно сделать in-memory таблицу с некоторыми ключами, чтобы ускорить поиск записи. Это будет работать примерно так: пусть в бд лежит 1024 sstable, из каждой 16 sstable сохраним в этой таблице 1 ключ. При запросе чтения будем смотреть среди этих 64 ключей и искать ближайший меньший запрашиваемого, так сможем уменьшить интервал sstable, на котором будет производиться бинпоиск записи, и что важно, уменьшим количество чтений с диска, таким образом.

2022-10-13 17:29 UTC, GaDiss approved these changes
15 баллов

2022-10-13 17:46 UTC, merged