Stage 1 Artur Galeev
polis-vk/2022-highload-dht pull request #24
Opened 2022-09-26 16:45 UTC by coradead

2022-09-27 15:09 UTC, Fedoresko requested changes
Цель вашей работы в том, чтобы запустить с профайлером вашу программу в разных режимах и проанализировать, как и когда она будет работать, что в принципе просиходит в тех или иных условиях, (частота запросов, размер записей, ограничения по памяти, количества уже записанного, рандомных или последовательнях ключах и т. п.), и свое понимание отразить в отчете. Пожалуйста, позанимайтесь этим. Жду каких-то мыслей на тему. Картинки тут не результат, а аргумент!

2022-09-27 15:09 UTC, Fedoresko commented on src/main/java/ok/dht/test/galeev/reports/stage1/results.md
> +![get graph](./PNGs/GetHistogram.png)
Почему столько времени ваше приложение выполняет метод AbstractMemorySegmentImpl.isSmall() Это какой-то тяжелый метод, или он блокируется? Попробуйте увеличить частоту сэмплирования в профайлере, и проверить.

2022-09-27 15:09 UTC, Fedoresko commented on src/main/java/ok/dht/test/galeev/reports/stage1/results.md
> +![put cpu](./PNGs/cpu_put.png)
Что за красные полоски? Там процессор был больше загружен, но почему?

2022-09-28 18:45 UTC, coradead commented on src/main/java/ok/dht/test/galeev/reports/stage1/results.md
> +После перебора кучи вариантов параметра `-R` - пришел к выводу, что это наиболее оптимальный
Я сделал около 6 замеров, если все приложить к отчету, то выходит слишком много

2022-09-28 18:47 UTC, coradead commented on src/main/java/ok/dht/test/galeev/reports/stage1/results.md
> +![get graph](./PNGs/GetHistogram.png)
У меня есть какая-то проблема с конвертором, ведь, если ставить меньшую частоту семплирования, то jfr2heat создает пустой график.

2022-09-28 18:51 UTC, coradead commented on src/main/java/ok/dht/test/galeev/reports/stage1/results.md
> +![put cpu](./PNGs/cpu_put.png)
Эти полоски - это код C++. В частности "Compile::Compile"

2022-09-28 18:55 UTC, coradead commented on src/main/java/ok/dht/test/galeev/DemoService.java
> +            = new Response(Response.BAD_REQUEST, Response.EMPTY);
Я исправил. Не мог предположить, что они immutable. Почитаю об этом в ближайшее время

2022-09-28 19:03 UTC, coradead commented on src/main/java/ok/dht/test/galeev/reports/stage1/results.md
> +![get graph](./PNGs/GetHistogram.png)
Я не знаю с чем это может быть связано

2022-09-29 00:52 UTC, coradead commented on src/main/java/ok/dht/test/galeev/reports/stage1/results.md
> +После перебора кучи вариантов параметра `-R` - пришел к выводу, что это наиболее оптимальный
Нам сказали, что если мы пристрелились - надо написать наиболее подходящий вариант, поэтому я не приклыдвал другие, но в новой версии - приложил 14К, в котором задержки выросли

2022-09-29 00:58 UTC, coradead commented
Я подумал, что нам дали wrk, profiler и хитмапу, чтобы установить, 'поигарться' с этим, а в ближайшем времени уже начать АНАЛИЗИРОВАТЬ данные. Постарался исправить и провести хоть какойто анализ

2022-09-29 13:04 UTC, Fedoresko approved these changes
Окей. Выводов недостаточно и с анализом ещё прилично по работать (9/15)

2022-09-29 13:06 UTC, coradead commented on src/main/java/ok/dht/test/galeev/reports/stage1/results.md
> +После перебора кучи вариантов параметра `-R` - пришел к выводу, что это наиболее оптимальный
Я в отчете прожил задержки при рейте в 14к и добавил, что при увеличении параметра `-R` всего на 500 - задержки увеличиваются в 3 раза. Это не то? Я не понимаю, что мне сейчас необхадимо делать, просто, раньше мы показывали свое понимание кодом, а в политехе наука отчетов оставляет желать лучшего, и на данный момент я в тупике.

2022-09-29 13:07 UTC, coradead commented on src/main/java/ok/dht/test/galeev/reports/stage1/results.md
> +Ограничения по памяти мы не можем изменять, поэтому объективно оценить влияние объема ОЗУ мы не можем, но можем предположить, что это позволит операционной системе не сразу загружать файлы на жесткий
У меня линуск как система, а хип нам запретили менять

2022-09-29 13:22 UTC, coradead commented on src/main/java/ok/dht/test/galeev/reports/stage1/results.md
> +![put cpu](./PNGs/cpu_put.png)
На лекции сказали, что это прогревается JVM, но я не знаю почему это происходит в середине работы

2022-09-29 13:27 UTC, coradead commented on src/main/java/ok/dht/test/galeev/reports/stage1/results.md
> +![put cpu](./PNGs/cpu_put.png)
я могу предположить, что это jit компилит код

2022-10-21 13:10 UTC, closed without merging