Stage-1-Alexander-Kosnitskiy
polis-vk/2022-highload-dht pull request #25
Opened 2022-09-26 19:47 UTC by Sanerins

2022-09-28 15:07 UTC, incubos requested changes
Есть ряд вопросов и замечаний.

2022-09-28 15:07 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/WRK_PUT
> +wrk -d 10 -t 1 -c 1 -R 15000 -s put.lua "http://localhost:19234/v0"
Используем тот же `put.lua`? Не хватает его исходников.

2022-09-28 15:07 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/WRK_PUT
> +  Non-2xx or 3xx responses: 149932
Т.е. все ответы -- это ошибки, верно?

2022-09-28 15:07 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/WRK_PUT
> +  Non-2xx or 3xx responses: 159984
Аналогично все запросы завершились ошибками.

2022-09-28 15:07 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/WRL_GET
> +wrk -d 10 -t 1 -c 1 -R 700 "http://localhost:19234/v0/entity?id=1"
Мы стреляли по предварительно наполненной БД, в которой нет ключа `1`?

2022-09-28 15:07 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/WRL_GET
> +GET - лучший случай: ключ существует, запрашиваем один и тот же, кешируем файл с ключом
За счёт чего работает кеширование?

2022-09-28 15:07 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/WRL_GET
> +Transfer/sec:      1.13MB
Не хватает стрельбы, когда ключи существуют и они разные. Вряд ли исследованные варианты являются исчерпывающими на практике, верно?

2022-09-28 15:07 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/OnRusultReport.md
> +Заметим, что когда мы рассматриваем лучшие случаи - кешируем один и тот же файл снова и снова, база показывает результаты
Что значит "кешируем снова и снова"?

2022-09-28 15:07 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/OnRusultReport.md
> +с самого нового и заканчивая самым старым. Это занимает много времени от того и видим критическое падение производительности
Как можно было бы улучшить ситуацию, исходя из знаний, полученных в курсе NoSQL?

2022-09-28 15:07 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/OnRusultReport.md
> +асинхронно переходить к записи новых файлов на диск, отсюда и небольшая потеря в производительности, когда как в лучшем
Можно оценить "небольшую потерю производительности" в цифрах?

2022-09-28 15:07 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/OnRusultReport.md
> +асинхронно переходить к записи новых файлов на диск, отсюда и небольшая потеря в производительности, когда как в лучшем
Тестирование с разными ключами в работе как раз не описано.

2022-09-28 15:08 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/OnRusultReport.md
> +особенно учитывая, что в реальной жизни ключи скорее всего будут всегда разные, а так же будет много запросов на несуществующие ключи.
Тестирование с разными ключами в работе как раз не описано.

2022-09-28 17:48 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/ServiceImpl.java
> +    public void fillTheDao() {
Убрал этот метод. Заполнение базы в таком случае можно будет осуществить через wrk2. Тут - для большей производительности

2022-09-28 17:50 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/ServiceImpl.java
> +                Thread.sleep(100);
Чтобы база не задыхалась от слишком большого количества запросов. Sleep дейсвительно был слишком жестким, можно было сделать и поменьше. Теперь контролирую поток запросов через wrk2

2022-09-28 17:51 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/ServiceImpl.java
> +        return s == null ? null : s.toByteArray();
нет, но хотелось доп проверки на всякий случай)

2022-09-28 18:17 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/result/WRK_PUT
> +wrk -d 10 -t 1 -c 1 -R 15000 -s put.lua "http://localhost:19234/v0"
Менял просто содержание этого файла)
Исходники добавил, разные

2022-09-28 18:18 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/result/WRK_PUT
> +  Non-2xx or 3xx responses: 149932
Верно, нашел ошибку и поправил

2022-09-28 18:18 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/result/WRL_GET
> +wrk -d 10 -t 1 -c 1 -R 700 "http://localhost:19234/v0/entity?id=1"
Да, ключа один там не было, я проверял это в POSTMAN

2022-09-28 19:04 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/ServiceImpl.java
> +        memorySegmentDao.close();
Теперь останавливаю

2022-09-28 19:04 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/ServiceImpl.java
> +        memorySegmentDao = new MemorySegmentDao(new Config(config.workingDir(), 8388608));
Исправил

2022-09-28 19:04 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/ServiceImpl.java
> +        Entry<MemorySegment> entry = memorySegmentDao.get(fromString(id));
обработал

2022-09-28 19:04 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/ServiceImpl.java
> +        memorySegmentDao.upsert(new BaseEntry<>(fromString(id), fromBytes(request.getBody())));
обработал

2022-09-28 19:04 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/ServiceImpl.java
> +        memorySegmentDao.upsert(new BaseEntry<>(fromString(id), null));
обработал

2022-09-28 19:05 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/ServiceImpl.java
> +        return data == null ? null : MemorySegment.ofArray(data.toCharArray());
убрал

2022-09-28 19:05 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/ServiceImpl.java
> +        return bytes == null ? null : MemorySegment.ofArray(bytes);
убрал

2022-09-28 19:06 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/result/WRL_GET
> +Transfer/sec:      1.13MB
справедливое замечание

2022-09-28 19:23 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/result/WRL_GET
> +GET - лучший случай: ключ существует, запрашиваем один и тот же, кешируем файл с ключом
Кеширование происходит за счет того, что мы один раз находим нужный нам ключ по файлам и добавляем его в кеш, расписал по-подробнее в .md

2022-09-28 19:25 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/result/OnRusultReport.md
> +Заметим, что когда мы рассматриваем лучшие случаи - кешируем один и тот же файл снова и снова, база показывает результаты
Исправил, очень криво тут все описал

2022-09-28 19:27 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/result/OnRusultReport.md
> +с самого нового и заканчивая самым старым. Это занимает много времени от того и видим критическое падение производительности
Нам стоило бы реализовать фильтр Блума.
Если элемент существет в базе, то фильтр Блума никогда не обманет и скажет о его существовании
Если элемент не существует в базе, то фильтр Блума с высокой вероятностью скажет, что его там нет (но иногда может соврать)
Дополнение базы фильтром блума позволит существенно сократить время выполнения запросов с несущ. ключами

2022-09-28 19:28 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/result/OnRusultReport.md
> +асинхронно переходить к записи новых файлов на диск, отсюда и небольшая потеря в производительности, когда как в лучшем
Описал чуть ниже

2022-09-28 19:28 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/result/OnRusultReport.md
> +особенно учитывая, что в реальной жизни ключи скорее всего будут всегда разные, а так же будет много запросов на несуществующие ключи.
Описал

2022-09-28 19:56 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/result/WRK_PUT
> +wrk -d 10 -t 1 -c 1 -R 18000 -s put.lua "http://localhost:19234/v0/entity?id=1"
Заиспользовал данные пограничных стрельб в своем анализе

2022-09-28 20:01 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/ServerImpl.java
> +        } catch (Exception e) {
method/constructor should not explicitly throw java.lang.Exception :(

2022-09-29 14:42 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/ServiceImpl.java
> +        return s == null ? null : s.toByteArray();
Тогда лучше использовать `assert`, аннотацию `NotNull` или `Objects.requireNonNull()`. В каждом подходе есть свои плюсы и минусы, но распространять `null` -- самое неудачное решение.

2022-09-29 14:52 UTC, incubos requested changes
Стало гораздо лучше, но не хватает анализа результатов профилирования, а также есть дополнительные вопросы по отчёту и цифрам latency.

2022-09-29 14:52 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/OnResultReport.md
> +наилучшего случая максимальная адекватная нагрузка возрастает до 17000-18000 запросов в секунду.
Извиняюсь, что не написал в прошлый раз, но в отчёте не хватает анализа результатов профилирования (на что мы тратим ресурсы при различных нагрузках), а также идей/предложений по оптимизации.

2022-09-29 14:52 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/OnResultReport.md
> +которое при переходе с 800 на 900 запросов увеличилось в 4 раза - с 9 до 37 ms!
Чем можно объяснить этот рост?

2022-09-29 14:52 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/WRK_GET
> +    Latency     2.48ms  823.48us   8.82ms   81.96%
Чем можно объяснить то, что максимальное время в 4 раза больше среднего?

2022-09-29 14:52 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/WRK_GET
> +  Non-2xx or 3xx responses: 7000
Чем можно объяснить эти ошибки? И ниже тоже.

2022-09-29 16:16 UTC, Fedoresko commented on src/main/java/ok/dht/test/kosnitskiy/ServiceImpl.java
> +        return data == null ? null : MemorySegment.ofArray(data.toCharArray());
У кого-то я эту херню уже видел. Кто с кого содрал?

2022-10-02 21:17 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/result/WRK_GET
> +  Non-2xx or 3xx responses: 7000
Это нельзя назвать ошибкой - нам возвращается response `404 - Not Found`. Это является ожидаемым поведением, так как здесь мы тестируем случаи, когда ключ не существует, об этом нам такой ответ и сообщает
Снизу, когда мы тестируем "разные ID, в том числе и существующие" ситуация аналогичная, однако уже не все response `Non-2xx or 3xx`, как раз потому что существующие ключи в этом блоке тестирования тоже есть

2022-10-02 21:21 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/result/WRK_GET
> +    Latency     2.48ms  823.48us   8.82ms   81.96%
Это связано с тем, что максмальное время достигается в тот момент, когда нам пришел запрос на несуществующий ключ, которые тут тоже случаются, и для его поиска приходится пройтись по всем существующим файлам и выполнить в них бинарный поиск. В обычном случае, когда ключ существует, мы находим ближайший файл с этим ключом, чаще всего он не особо глубоко, ибо тут мы проходимся по ID, которые я дописывал в последние файлы PUT запросами, а потому для их нахождения мы проходимся только по 1-4 самым свежим файлам. От того такое поведение среднего времени

2022-10-02 21:25 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/result/OnResultReport.md
> +которое при переходе с 800 на 900 запросов увеличилось в 4 раза - с 9 до 37 ms!
Мне кажется, что это связано с тем, что из-за привышения пропускной способности нашей базы данных, начинают образовываться сильные пробки, когда сразу куча запросов стоят в очереди на обработку, ну и последний запрос, который находится в этой очереди, как раз и имеет такое огромное MAX время выполнения, так как оно включает в себя все то время, что он прождал пока настанет его очередь на выполнение. Ну и при переходе с 800 на 900 такие очереди стали намного длиннее, оттого и так сильно повысилось максимальное время

2022-10-03 16:05 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/OnResultReport.md
> +наилучшего случая максимальная адекватная нагрузка возрастает до 17000-18000 запросов в секунду.
Ждать дополнения отчёта или оцениваем как есть?

2022-10-03 18:26 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/result/OnResultReport.md
> +наилучшего случая максимальная адекватная нагрузка возрастает до 17000-18000 запросов в секунду.
Ой, сейчас тогда дополню отчёт, просто думал, что уже нельзя дополнять, так как была лекция-пояснение

2022-10-03 23:37 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/result/OnResultReport.md
> +наилучшего случая максимальная адекватная нагрузка возрастает до 17000-18000 запросов в секунду.
Дополнил отчет, постарался написать что-то интересное, а не только то, что было сказано на лекции

2022-10-04 14:14 UTC, incubos approved these changes
12 баллов.

2022-10-04 14:14 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/OnResultReport.md
> +однако это, конечно, больше из разряда фантастики наверное
Вы не поверите, но примерно так и работает. На профилях мы видим работу JIT в отдельном CompilationThread.

2022-10-04 14:14 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/OnResultReport.md
> +где процессор загружен не особо сильно, здесь график загрузки процессора почти весь красный, так что просижевающего ресурса
Здесь краснота говорит не об утилизации процессора, а о количестве ивентов сэмплирования относительно других временных точек. Думаю, стоит поднять этот вопрос на очередном занятии и попросить Артёма ещё раз объяснить.

2022-10-04 14:14 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/OnResultReport.md
> +приходит видеокарта, а тут, в GET запросах, нам все же нужны будут нормальные, высокопроизводительные ядра, чтобы работать
Видеокарта вряд ли подойдёт, но это тема отдельной дискуссии, а вот асинхронность позволила бы нам утилизировать и CPU, и устройство ввода-вывода.

2022-10-04 14:14 UTC, incubos commented on src/main/java/ok/dht/test/kosnitskiy/result/OnResultReport.md
> +вероятно джит будет перекомпилировать части нашего сервера на постоянной основе, а потому думать над оптимизацией поведения
Это не так работает. Если очень сильно упрощать (и в целом, это не очень корректно говорить), в итоге JIT будет "ориентироваться" на исполнение горячего кода.

2022-10-04 17:53 UTC, Sanerins commented on src/main/java/ok/dht/test/kosnitskiy/result/OnResultReport.md
> +вероятно джит будет перекомпилировать части нашего сервера на постоянной основе, а потому думать над оптимизацией поведения
Просто я тут к тому, что в зависимости от нагрузки и вида нагрузки (PUT/GET запросы), у нас у сервера будет меняться код, который является наиболее горячим. Мол в одно время горячим будет одна часть кода, а в другое время - совсем другая. Поэтому возможно Джит будет это замечать и пытаться перекомпилировать код для лучшего соответствия новой горячести

2022-10-07 12:08 UTC, incubos requested changes
Тест пофиксите?

2022-10-11 09:28 UTC, merged