Stage 1 Kiselyov Alexander
polis-vk/2022-highload-dht pull request #31
Opened 2022-09-27 02:08 UTC by AlexanderKiselyov

2022-09-29 13:03 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +        BaseEntry<byte[]> result = dao.get(id.getBytes(StandardCharsets.UTF_8));
Не хватает обработки ошибок.

2022-09-29 13:03 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +        dao.upsert(new BaseEntry<>(id.getBytes(StandardCharsets.UTF_8), putRequest.getBody()));
Не хватает обработки ошибок.

2022-09-29 13:03 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +        dao.upsert(new BaseEntry<>(id.getBytes(StandardCharsets.UTF_8), null));
Не хватает обработки ошибок.

2022-09-29 13:05 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Non-2xx or 3xx responses: 4799348
Откуда ошибки?

2022-09-29 13:05 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +> $
Какие параметры запуска?

2022-09-29 13:06 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Non-2xx or 3xx responses: 5399790
Откуда эти ошибки?

2022-09-29 13:07 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +составляет примерно 2.11s. 90% запросов выполняются за 5.82s в среднем, а 99% - за 6.39s. При скорости обработки
`ms`, а не `s` -- как и выше и ниже, верно?

2022-09-29 13:08 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Get:
На `GET` запросах видно большое число ошибок? Либо их не должно быть, либо это необходимо объяснить.

2022-09-29 13:08 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +
Хотелось бы увидеть предложения по улучшению/оптимизации текущего решения.

2022-09-29 13:09 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +составляет примерно 0.83s. 90% запросов выполняются за 1.12s в среднем, а 99% - за 15.04s. При скорости обработки
Чем вызван рост времени на высоких перцентилях? И в случае `GET` тоже.

2022-09-29 13:11 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Приблизительно 50% памяти расходуется на библиотеку one-nio. Здесь необходимо создать сессию, обработать http
В `get_alloc.html` все аллокации ведут в `PriorityQueue` -- это расходится с тем, что написано в отчёте. Поясните?

2022-09-29 13:13 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Процессорное время делится следующим образом: примерно 55% времени занимает работа по поиску записей в БД, еще около
В `get_cpu.html` 80% ресурсов уходит на G1. Почему? Почему это не отражено здесь?

2022-09-29 13:14 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Процессорное время делится следующим образом: примерно 40% времени занимает работа библиотеки one-nio, еще около 35% -
В `put_cpu.html` 40% ресурсов уходит на G1. Почему? Почему это не отражено в отчёте?

2022-09-29 13:15 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Память по большей части (приблизительно 95%) выделяется под библиотеку one-nio. Эта память расходуется на создание
В `put_alloc.html` всё выглядит иначе. Можете объяснить?

2022-09-29 13:16 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Процессорное время делится следующим образом: примерно 40% времени занимает работа библиотеки one-nio, еще около 35% -
На что именно внутри `one-nio`?

2022-09-29 13:16 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Память по большей части (приблизительно 95%) выделяется под библиотеку one-nio. Эта память расходуется на создание
На что именно выделяется память? Здесь приведены общие слова про работу любого HTTP сервера.

2022-10-02 22:18 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +        BaseEntry<byte[]> result = dao.get(id.getBytes(StandardCharsets.UTF_8));
исправил

2022-10-02 22:18 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +        dao.upsert(new BaseEntry<>(id.getBytes(StandardCharsets.UTF_8), putRequest.getBody()));
исправил

2022-10-02 22:18 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +        dao.upsert(new BaseEntry<>(id.getBytes(StandardCharsets.UTF_8), null));
исправил

2022-10-02 22:18 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Non-2xx or 3xx responses: 4799348
изменил файл get.lua

2022-10-02 22:19 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +> $
исправил

2022-10-02 22:19 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Non-2xx or 3xx responses: 5399790
изменил файл get.lua

2022-10-02 22:19 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +составляет примерно 2.11s. 90% запросов выполняются за 5.82s в среднем, а 99% - за 6.39s. При скорости обработки
исправил

2022-10-02 22:19 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Get:
исправил

2022-10-02 22:19 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +
описал в отчете

2022-10-02 22:19 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +составляет примерно 0.83s. 90% запросов выполняются за 1.12s в среднем, а 99% - за 15.04s. При скорости обработки
описал в отчете

2022-10-02 22:19 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Приблизительно 50% памяти расходуется на библиотеку one-nio. Здесь необходимо создать сессию, обработать http
описал в отчете

2022-10-02 22:20 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Процессорное время делится следующим образом: примерно 55% времени занимает работа по поиску записей в БД, еще около
описал в отчете

2022-10-02 22:20 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Процессорное время делится следующим образом: примерно 40% времени занимает работа библиотеки one-nio, еще около 35% -
описал в отчете

2022-10-02 22:20 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Память по большей части (приблизительно 95%) выделяется под библиотеку one-nio. Эта память расходуется на создание
описал в отчете

2022-10-02 22:20 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Процессорное время делится следующим образом: примерно 40% времени занимает работа библиотеки one-nio, еще около 35% -
описал в отчете

2022-10-02 22:20 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Память по большей части (приблизительно 95%) выделяется под библиотеку one-nio. Эта память расходуется на создание
описал в отчете

2022-10-03 16:52 UTC, incubos requested changes
Есть вопросы.

2022-10-03 16:52 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +    static Logger logger = Logger.getLogger(WebService.class);
Не хватает `private` и `final`.

2022-10-03 16:52 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            logger.fatal("GET operation from GET request with id " + id + " failed: " + e.getMessage());
Почему `fatal`, а не `error`? Разве мы не можем продолжать работу?

2022-10-03 16:52 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            logger.fatal("GET operation from GET request with id " + id + " failed: " + e.getMessage());
Чтобы избежать лишних аллокаций в случае выключенного логгирования, используют placeholderы, а также `Logger` сам понимает последний аргумент типа `Throwable`:
```java
logger.error("GET operation from GET request with id {} failed", id, e);
```

2022-10-03 16:52 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            logger.fatal("UPSERT operation from PUT request with id " + id + " failed: " + e.getMessage());
Placeholders.

2022-10-03 16:52 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            logger.fatal("UPSERT operation from DELETE request with id " + id + " failed: " + e.getMessage());
Placeholders.

2022-10-03 16:52 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            logger.fatal("GET operation with id " + id + " from GET request failed: " + e.getMessage());
Почему `fatal`, а не `error`? Разве мы не можем продолжать работу?

2022-10-03 16:52 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            logger.fatal("GET operation with id " + id + " from GET request failed: " + e.getMessage());
Чтобы избежать лишних аллокаций в случае выключенного логгирования, используют placeholderы, а также `Logger` сам понимает последний аргумент типа `Throwable`:
```java
logger.error("GET operation from GET request with id {} failed", id, e);
```

2022-10-03 16:52 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            logger.fatal("UPSERT operation with id " + id + " from PUT request failed: " + e.getMessage());
`error` и placeholders.

2022-10-03 16:52 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            logger.fatal("UPSERT operation with id " + id + " from DELETE request failed: " + e.getMessage());
`error` и placeholders.

2022-10-03 16:52 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Оставшееся время (приблизительно 60%) приходится на JIT-компиляцию и flush данных (особенно на поздних этапах, когда
JIT компиляция в профилях свидетельствует о недостаточном прогреве, разве нет?

2022-10-03 16:52 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +записи становятся очень длинными и приходится часто обращаться к памяти).
Можете пояснить фразу "записи становятся очень длинными и приходится часто обращаться к памяти"?

2022-10-03 16:52 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +класса one.nio.net.Session. Данный объект представляет собой набор данных, которые передаются клиентом и оборачиваются
Не "передаются клиентом", а стоят в очереди на отправку **клиенту**. Вы ведь не смотрели код `one-nio`?

2022-10-03 16:52 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +удаления). Наибольшую проблему представляют селекторы, которые блокируются при большом количестве попыток соединения
Я рад, что с последнего занятия что-то отложилось, но можете объяснить, пожалуйста, как вы увидели эту "наибольшую проблему" на ваших профилях?

2022-10-03 16:52 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +
Других идей, кроме асинхронной обработки запросов, которую предстоит реализовать на следующем этапе, не появилось?

2022-10-03 19:31 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +    static Logger logger = Logger.getLogger(WebService.class);
исправил

2022-10-03 19:31 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            logger.fatal("GET operation from GET request with id " + id + " failed: " + e.getMessage());
исправил

2022-10-03 19:31 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            logger.fatal("GET operation from GET request with id " + id + " failed: " + e.getMessage());
исправил

2022-10-03 19:31 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            logger.fatal("UPSERT operation from PUT request with id " + id + " failed: " + e.getMessage());
исправил

2022-10-03 19:31 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            logger.fatal("UPSERT operation from DELETE request with id " + id + " failed: " + e.getMessage());
исправил

2022-10-03 19:31 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            logger.fatal("GET operation with id " + id + " from GET request failed: " + e.getMessage());
исправил

2022-10-03 19:32 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            logger.fatal("GET operation with id " + id + " from GET request failed: " + e.getMessage());
исправил

2022-10-03 19:32 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            logger.fatal("UPSERT operation with id " + id + " from PUT request failed: " + e.getMessage());
исправил

2022-10-03 19:32 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            logger.fatal("UPSERT operation with id " + id + " from DELETE request failed: " + e.getMessage());
исправил

2022-10-03 19:32 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Оставшееся время (приблизительно 60%) приходится на JIT-компиляцию и flush данных (особенно на поздних этапах, когда
исправил в отчете

2022-10-03 19:32 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +записи становятся очень длинными и приходится часто обращаться к памяти).
исправил в отчете

2022-10-03 19:32 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +класса one.nio.net.Session. Данный объект представляет собой набор данных, которые передаются клиентом и оборачиваются
исправил в отчете

2022-10-03 19:32 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +удаления). Наибольшую проблему представляют селекторы, которые блокируются при большом количестве попыток соединения
исправил в отчете

2022-10-03 19:36 UTC, AlexanderKiselyov commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +
дополнил для get и put

2022-10-04 14:18 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            LOGGER.error(String.format("GET operation with id %s from GET request failed.", id), e);
Посмотрите интерфейс `Logger`. В текущем решении проблема осталась, а можно лучше вот так:
```java
LOGGER.error("GET operation with id {} from GET request failed.", id, e);
```

2022-10-04 14:18 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            LOGGER.error(String.format("UPSERT operation with id %s from PUT request failed.", id), e);
Здесь тоже.

2022-10-04 14:18 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            LOGGER.error(String.format("UPSERT operation with id %s from DELETE request failed.", id), e);
И здесь.

2022-10-04 14:18 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/WebService.java
> +            logger.fatal("GET operation from GET request with id " + id + " failed: " + e.getMessage());
Не так. Я ведь даже привёл пример.

2022-10-04 14:19 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +Оставшееся время (приблизительно 60%) приходится на JIT-компиляцию и flush данных (особенно на поздних этапах, когда
Вы просто заменили JIT на "системные вызовы"?

2022-10-04 14:33 UTC, incubos approved these changes
12 баллов.

2022-10-04 14:33 UTC, incubos commented on src/main/java/ok/dht/test/kiselyov/report/report.md
> +операции фонового flush. Данный порог можно увеличить, что положительно скажется на производительности системы.
Но разве паузы не станут длиннее, пусть и реже?

2022-10-07 12:54 UTC, incubos approved these changes

2022-10-07 16:31 UTC, merged