Stage 1 Yasevich Artem
polis-vk/2022-highload-dht pull request #32
Opened 2022-09-27 19:41 UTC by a-yasevich

2022-09-28 14:08 UTC, Fedoresko reviewed
Ждем отчет. Не забудьте протестировать ваш сервис на разного рода нагрузке. Мы хотим видеть в отчете результат анализа данных wrk и профайлера. То есть что полезного вы смогли из этого понять о своем сервисе.

2022-09-28 14:08 UTC, Fedoresko commented on src/main/java/ok/dht/test/yasevich/ServiceImpl.java
> +        return data == null ? null : MemorySegment.ofArray(data.toCharArray());
Когда здесь может быт null, и что будет в этом случае дальше?

2022-09-28 14:08 UTC, Fedoresko commented on src/main/java/ok/dht/test/yasevich/ServiceImpl.java
> +    @ServiceFactory(stage = 1, week = 1)
У вас с бонусом или нет?

2022-09-28 14:08 UTC, Fedoresko commented on src/main/java/ok/dht/test/yasevich/profiling/scripts/put.lua
> +    path = "/v0/entity?id=key" .. id
Какая вероятность получить тут какие-то данные, которые есть в базе?

2022-09-28 14:10 UTC, Fedoresko requested changes
В общем, поканет отчета, а он нужен.

2022-09-28 19:08 UTC, a-yasevich commented
Отчёт https://github.com/polis-vk/2022-highload-dht/pull/32/files#diff-fc66d6a9eb0d8581eafbbb2134a394364ed0369148fc58b993e15cff0091c30b

2022-09-28 19:10 UTC, a-yasevich commented on src/main/java/ok/dht/test/yasevich/ServiceImpl.java
> +    @ServiceFactory(stage = 1, week = 1)
Вроде с бонусом)

2022-09-28 19:11 UTC, a-yasevich commented on src/main/java/ok/dht/test/yasevich/ServiceImpl.java
> +        return data == null ? null : MemorySegment.ofArray(data.toCharArray());
По идее никогда)

2022-09-29 14:20 UTC, Fedoresko approved these changes
Окей. Хотелось видеть больше интересного в выводах, например, что можно сделать лучше. (12/15)

2022-09-29 14:20 UTC, Fedoresko commented on src/main/java/ok/dht/test/yasevich/profiling/report.md
> +* cpu профилирование показывает, что GC работал активнее прежнего, запустив полную сборку мусора (часто менялся state и в памяти стало много ConcurrentSkipList мап без ссылок на них)
Я вижу, что и в get просто (1?) GC запускается часто. По-видимому это не full gc, однако все равно можно ли как-то уменьшить количество запусков?

2022-09-29 14:20 UTC, Fedoresko commented on src/main/java/ok/dht/test/yasevich/profiling/report.md
> +Увидели на практике, что наш storage имеет бОльшую производительность на put запросы и при этом flushThreshold на них не так сильно влияет, как на get запросы
Так что в итоге, какой бы вы выбрали flushThreshold и почему, раз вы его тестировали? Или может быть тут есть ещё факторы, которые влияют на выбор?

2022-09-29 14:20 UTC, Fedoresko commented on src/main/java/ok/dht/test/yasevich/profiling/report.md
> +Что объяснимо, так как нам требуется log(n) произвольных доступов на поиск (где n - число записей), и потом одним читаем
В конечном итоге сколько получается обращений к диску?

2022-10-21 15:05 UTC, closed without merging