stage-1 Skroba Dmitriy ITMO
polis-vk/2022-highload-dht pull request #43
Opened 2022-09-28 19:02 UTC by Sdmitrioul

2022-10-04 13:02 UTC, GaDiss requested changes
**build.gradle и содержимое папки drozdov в PR со своим решением менять не стоит**
Codeclimate жалуется на последний коммит!!!

2022-10-04 15:19 UTC, Sdmitrioul commented on src/main/java/ok/dht/test/skroba/MyServiceImpl.java
> +        server.addRequestHandlers(this);
поправил

2022-10-04 15:52 UTC, Sdmitrioul commented on src/main/java/ok/dht/test/skroba/report/scripts/put.lua
> +    url = "/v0/entity?id=" .. math.random(1, 5000)
Тк у меня 10000 запросов, я хотел сделать распределение по id +- равномерным, но иногда с перезаписью данных, поэтому взял 5000

2022-10-05 10:04 UTC, Sdmitrioul commented on src/main/java/ok/dht/test/skroba/report/firstStageReport.md
> +  Non-2xx or 3xx responses: 207365
Потому что нет сущностей с данной id в базе данных

2022-10-05 12:24 UTC, Sdmitrioul commented on src/main/java/ok/dht/test/skroba/report/firstStageReport.md
> +`wrk2 -t 1 -c 1 -d 30s -R 10000 http://localhost:3000 -s put.lua`
Исправил

2022-10-05 12:24 UTC, Sdmitrioul commented on src/main/java/ok/dht/test/skroba/report/firstStageReport.md
> +`wrk2 -t 1 -c 1 -d 30s -R 10000 http://localhost:3000 -s get.lua`
Исправил

2022-10-05 12:26 UTC, Sdmitrioul commented on src/main/java/ok/dht/test/skroba/report/firstStageReport.md
> +alloc.html слишком тяжелый, поэтому не клал в репозиторий.
Поправил отчет

2022-10-05 12:28 UTC, Sdmitrioul commented on src/main/java/ok/dht/test/skroba/report/firstStageReport.md
> +alloc.html слишком тяжелый, поэтому не клал в репозиторий.
Дополнительно: по анализу других запусков wrk, когда наш сервис начинает захлебываться видно, что это связано, не столько с бд, а сколько с тем, что мы долго обрабатываем запрос, тк графики части бд не сильно изменились. Для проверки, я у себя поставил 30000 запросов на тот же промежуток времени

2022-10-13 15:35 UTC, GaDiss approved these changes
10 баллов. В отчёте проведено недостаточно анализа используемой реализации БД и найдено мало недостатков.

2022-10-13 15:35 UTC, GaDiss commented on src/main/java/ok/dht/test/skroba/report/firstStageReport.md
> +Если смотреть на исполнение запросов, видно что большая часть времени уходит не на работу с сетью(работу с сетью мы не с оптимизируем), а на обработку запросов, конвертация строк, аллокации массивов.
Если не исправить изменениями в сервере, стоит написать, как можно исправить изменениями в самой БД.

2022-10-13 15:42 UTC, merged