Stage 1 Labazov Artem
polis-vk/2022-highload-dht pull request #46
Opened 2022-09-28 20:12 UTC by artem

2022-10-04 13:03 UTC, GaDiss requested changes
Надо резрешить конфликты с основной веткой: менять содержимое папки drozdov не следует в PR со своим решением

2022-10-05 19:02 UTC, artem commented on src/main/java/ok/dht/test/labazov/report/s1w1.md
> +* При `GET` нагрузке аллокации и процессорное время тратятся на чтение данных с диска.
Добавил больше пояснений

2022-10-05 19:02 UTC, artem commented on src/main/java/ok/dht/test/labazov/report/s1w1.md
> +    Latency     3.86ms    7.45ms  44.35ms   89.35%
Там хотспон компилировал код, статистический недочёт. Прогнал заново с более долгим временем измерения

2022-10-05 19:02 UTC, artem commented on src/main/java/ok/dht/test/labazov/HttpApi.java
> +        return data == null ? null : MemorySegment.ofArray(data.toCharArray());
Убрал проверку

2022-10-05 19:02 UTC, artem commented on src/main/java/ok/dht/test/labazov/HttpApi.java
> +            dao = new MemorySegmentDao(new Config(config.workingDir(), 8 * 1024 * 1024));
Исправил

2022-10-05 19:02 UTC, artem commented on src/main/java/ok/dht/test/labazov/HttpApi.java
> +    private static final Response HTTP_BAD_REQUEST = new Response(Response.BAD_REQUEST, Response.EMPTY);
Исправил

2022-10-13 16:33 UTC, GaDiss approved these changes
Хорошо протестировал, но объяснения и гипотезы по оптимизации слабые. 8 баллов

2022-10-13 17:09 UTC, merged