Kovalenko Pavel
polis-vk/2022-highload-dht pull request #49
Opened 2022-09-28 20:32 UTC by PaaavelZ

2022-10-04 11:23 UTC, incubos requested changes
Есть множество вопросов и замечаний.

2022-10-04 11:23 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +../wrk2/wrk -c 1 -d 60s -t 1 -R 500 -L http://localhost:19234/v0/entity -s get-existing-random.lua
Зачем стрелять на 500rps, если уже выше было понятно?
```
Requests/sec:    113.55
```

2022-10-04 11:23 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +  Non-2xx or 3xx responses: 100
Откуда берутся эти ошибки?

2022-10-04 11:23 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +    Latency    69.38ms  129.55ms 679.42ms   89.50%
Можете объяснить такой разброс времени?

2022-10-04 11:23 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +На гистограмме ниже видно, что разрыв по латенси между рейтом 100 и 500 огромен,
Ещё на первой стрельбе было понятно, что сервис смог втащить только 123rps...

2022-10-04 11:23 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +    Latency   760.62us  559.65us  27.60ms   97.24%
Чем можно объяснить такое большое значение Max?

2022-10-04 11:23 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +Одним из решений этой проблемы является перенос самого по себе диапазона ключей в мета-информацию
Не рассматривали вариант хранения min/max ключей в heap рядом с каждым открытым SSTable? Открываем файлы мы относительно редко и в этот момент можно извлечь из них 2 ключа. Чем плох такой подход?

2022-10-04 11:23 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +из-за них и появился этот огромный Jit-пласт.
На этом профиле нет никакого JIT -- мы ведь смотрим на аллокации памяти. И тут нет никакой магии: этот "пласт" растёт из вашего метода `FileUtils.nFiles()`, где вы потоково **на каждый запрос** сканируете все файлы и резолвите путь в ФС **для каждого из них** -- как это можно соптимизировать?

2022-10-04 11:23 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +аллокаций на 50к запросах - их неимоверно много:
Вы ведь выше выяснили, что система не держит 50Krps -- зачем профилировать на этой нагрузке, т.е. профилировать перегруженную систему? Инсайты, которые вы извлечёте, будут использованы для оптимизации перегруженной системы, чего в реальности никто не будет допускать.

2022-10-04 11:23 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +при двух рейтах - 500 и 5к. На рейте 500 видна "отсрочка" увеличения времени ответа
Давайте более техническим языком (без "хлопков" и "отрицательного роста")? :) Например, 0.1% запросов на нагрузке в 500rps уже не укладывается в 5 мс.

2022-10-04 11:23 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +![](./get/latency/get_hist_nonexisting.png)
На этом графике есть интересный момент -- почему 99.99% перцентиль 500rps выше чем 5Krps?

2022-10-04 11:23 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +Requests/sec:     46.02
100rps система не смогла.

2022-10-04 11:23 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +Requests/sec:     57.54
500rps не смогла и подавно. Зачем эта стрельба?

2022-10-04 11:23 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +Поскольку вероятность появления существующего и несуществующего ключей одна и та же (50/50),
Если придираться, то не 50/50, потому что вы заливали ключи от 1 до 100М, а стреляли в диапазоне от 10М до 200М, верно?

2022-10-04 11:23 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +уже на райте 100 видим "взрыв" времени ответа нашей БД на 0 перцентилях.
Конечно, мы ведь даже 100rps не смогли вытянуть.

2022-10-04 11:23 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +которые считаются нормальными в современном мире.
Можете раскрыть мысль в цифрах?

2022-10-04 11:23 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +по памяти и по диску, а вот на CPU нагрузка идёт всегда, где-то разреженная, где-то учащённая
Можете конкретизировать в коде фразу "CPU нагрузка идёт всегда, где-то разреженная, где-то учащённая"? Это очень общее утверждение.

2022-10-04 11:30 UTC, incubos requested changes
Добавил замечания по `PUT` в дополнение к предыдущим. В целом, в отчёте описано развёрнутое нагрузочное тестирование (впрочем, не всегда корректно), но к сожалению присутствует очень много общих слов и мало конкретики (что за код является проблемным, на что именно расходуются ресурсы, как можно улучшить ситуацию). Кроме упоминания BloomFilter и реализованной оптимизации с min/max ключами.

2022-10-04 11:30 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +    Latency   817.73us    3.00ms 107.78ms   99.60%
Можете объяснить такое высокое значение Max?

2022-10-04 11:30 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +На 10к уже наблюдем "подзахлёб", когда среднее латенси становится больше 1мс:
Нагрузку выдержали же, ошибок нет. Чем можно объяснить рост среднего времени?

2022-10-04 11:30 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +![](./put/heatmap/put_cpu_50k.png)
Снова профилируем перегруженную систему. Это неправильно, как указывалось выше.

2022-10-04 11:30 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +невооружённым глазом видно, что все ресурсы компьютера уходят именно на саму обработку
На `NativeSocket.write()` уходит не больше трети CPU. Можете проанализировать всё остальное и предложить варианты улучшения?

2022-10-04 11:30 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +Видно, что при заданных путах повышение латенси наблюдается в районе 95 перцентилей.
С чем он может быть связан?

2022-10-04 12:53 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/get/scripts/get-existing-random.lua
> +    local r = math.random(1, 100000000-1)
Это у нас нумерация до 99млн999тыс999 элемента, не нашёл, как в Lua красиво можно было бы разделить большие числа, а я их постоянно менял, ибо тестировал то выборку по одному и тому же ключу, то выборку по разным ключам. Сейчас понимаю, что лучше бы было завести 2 разных файла под это.

2022-10-04 13:12 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/MyService.java
> +            this.server.addRequestHandlers(this);
Исправил.

2022-10-04 13:38 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/MyService.java
> +            throw new RuntimeException(e);
Интересный подход. Но у нас и так, и так исключение выбросится в main, откуда запускался наш сервер, однако мы можем провести проверку на то, что Future зафейленным пришёл, и как-то что-то уже предпринимать, ибо знаем источник. Исправил.

2022-10-04 13:45 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +способна переварить 5к запросов в секунду.
В ТамТаме, по моей памяти, говорили о том, что для отчёта нужно рассматривать крайние случаи (то есть когда система работает супер-быстро, латенси измеряется в микросекундах и т.д., или же когда система уходит в отказ - перенагружена). Может, я неправильно понял, что нужно предоставлять тогда в отчёте, но я бы с радостью привёл тут стрельбу на 5к.

2022-10-04 13:53 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/get/scripts/get-existing-random.lua
> +    local r = math.random(1, 100000000-1)
Исправил.

2022-10-04 19:39 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +    Latency     1.32ms    1.24ms  33.15ms   95.69%
Поскольку нагрузка стабильная (судим ещё и по хитмапе), то нужно искать участки с заметно выделяющимися красными точками. В нашем случае такая красная точка одна, и в ней происходит компиляция селектор треда. Судя по всему, "неудачный" гет запрос, у которого латенси была максимальная, пришёлся на этот момент. Исправить это нельзя, а в целом по хитмапе видно много зелёных участков (нашего кода), который естественным образом можно оптимизировать, например, метод nFiles, который при каждом обращении get лезет на диск подсчитывать количество хранимых файлов. Как это можно оптимизировать, приведу в соответствующем комментарии.
![image](https://user-images.githubusercontent.com/76079492/193910073-aed28c80-4755-4461-8056-8e3f0de9f010.png)
![image](https://user-images.githubusercontent.com/76079492/193910110-ea5ed74f-dedc-468e-bdb6-8751f068ba7e.png)

2022-10-04 19:42 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +../wrk2/wrk -c 1 -d 60s -t 1 -R 500 -L http://localhost:19234/v0/entity -s get-existing-random.lua
Я искренне прошу прощения, на некоторые числа в определённых областях (max latency, rps) просто не обращал внимания, смотрел в основном на avg latency и количество принятых запросов ("total"). Сейчас понимаю, что нужно учитывать и все остальные числа, отражу это в отчёте.

2022-10-04 19:46 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +  Non-2xx or 3xx responses: 100
Судя по соотношению количество запросов/количество ошибок, это статистическая погрешность :) Если по-честному, я только сейчас узнал, что у меня на диске записывалось почему-то не 100млн энтрей, а 97млн, и, стоит полагать, нормальное распределение пару (сотен) раз затронуло область [97млн;100млн]. В файлике get_existing_random.lua видим, что мы действительно рандомим до 100млн.
![image](https://user-images.githubusercontent.com/76079492/193911659-a4a982c5-f15d-4cd2-ba6d-69deca03d255.png)
Отчёт буду переписывать.

2022-10-04 19:53 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +    Latency     1.32ms    1.24ms  33.15ms   95.69%
Дополнительно отражу анализ подобного рода в отчёте.

2022-10-04 19:56 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +    Latency    69.38ms  129.55ms 679.42ms   89.50%
К сожалению, моя хитмапа по гету получилась настолько сумбурной, что даже я сам едва ли могу в ней ориентироваться. Построю для каждой вариации свою хитмапу, чтобы легче было понимать, с чем имеем дело, и обязательно объясню.

2022-10-04 19:57 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +На гистограмме ниже видно, что разрыв по латенси между рейтом 100 и 500 огромен,
Ответил чуть выше о корне этой ошибки.

2022-10-04 19:58 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +    Latency   760.62us  559.65us  27.60ms   97.24%
И тут тоже проблемы с разделением хитмап. Перепишу полностью весь отчёт.

2022-10-04 19:59 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +Одним из решений этой проблемы является перенос самого по себе диапазона ключей в мета-информацию
Это отличное предложение! Спасибо. Уже реализовал в своём дао, прирост производительности - как минимум, в 4 раза.

2022-10-04 20:09 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +Одним из решений этой проблемы является перенос самого по себе диапазона ключей в мета-информацию
Также я думал в рамках key-range оптимизации о левелинге - то есть о структурированном хранении файлов, разделяя их на "старые" и "новые" как бы по уровням. На уровне "новых" файлов данные внутри упорядочены (по сути те же SSTable), но сами файлы не упорядочены и могут содержать пересекающиеся множества ключей (то есть чтобы сказать, что ключа нет, нужно обойти все файлы). На уровне "старых" файлов хранятся скомпакченные данные, файлы не содержат пересекающихся множеств, и поэтому если ключ, по которому мы ищем, меньше минимального в файле (в ренже), то мы просто дальше не идём и не просматриваем все N ренжей.

2022-10-04 20:59 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +из-за них и появился этот огромный Jit-пласт.
В первый раз я пытался это реализовать через атомик, не удалось. Решил пойти по пути наименьшего сопротивления и создавать сисколы на каждый вызов гета, что мне и аукнулось. Сейчас снова переделал на атомики (каждая сущность, создающая или удаляющая какой-либо файл с диска, сообщает об этом централизовано в FileUtils, который инкрементирует/декрементирует значение счётчика). Таким образом, удалось добиться большей производительности.

2022-10-04 21:20 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +аллокаций на 50к запросах - их неимоверно много:
Чуть выше описал истоки этой ошибки.

2022-10-04 21:30 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +![](./get/latency/get_hist_nonexisting.png)
И снова нет пока возможности ответить, ибо хитмапы надо разделять и перестраивать. Но я учту это при переписывании отчёта.

2022-10-04 21:33 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +Поскольку вероятность появления существующего и несуществующего ключей одна и та же (50/50),
Верно. Исказил факты, так как не хотел перезаполнять базу на 3ГБ (изменился алгоритм записи в файлы). Сейчас уже переборол это, и новый отчёт не будет лукавить.

2022-10-04 21:35 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +по памяти и по диску, а вот на CPU нагрузка идёт всегда, где-то разреженная, где-то учащённая
Имел в виду, что нагрузка стабильная, просто где-то мы работаем на пределе возможностей нашей базы, а где-то выжимаем самый минимум.

2022-10-04 21:37 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +которые считаются нормальными в современном мире.
Это я пытался оправдать свою неоптимальную реализацию NoSQL-БД, при исправлении замечаний понял, что существует ещё уйма оптимизаций, что уже улучшили или могут в перспективе улучшить перформанс в десятки раз. Онное в отчёте неуместно, уберу.

2022-10-04 21:55 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +    Latency   817.73us    3.00ms 107.78ms   99.60%
В первой половине нашей нагрузки на хитмапе видно, что 50% (а всего - 25%) времени процессора отнимает компиляция потоков (судя по всему, селектор тредов, поскольку сами мы бьём в один поток). Стоит полагать, какая-то часть путов попала на эту компиляцию, что сделало латенси большим. Видно во второй половине первой половины (второй четверти) хитмапы, что база уже принимает запросы, ибо готова к работе.
![image](https://user-images.githubusercontent.com/76079492/193937085-44624779-5e72-45de-a832-651058bc2d2f.png)
Вместе с тем после завершения компиляции у нас появляется больше ресурсов для обработки запросов, поэтому они проходят быстрее.
![image](https://user-images.githubusercontent.com/76079492/193937212-7800025f-d96c-4689-a393-d75b4bf4df6e.png)

2022-10-04 22:11 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +На 10к уже наблюдем "подзахлёб", когда среднее латенси становится больше 1мс:
Флашами, сборкой мусора и компиляцией ранее нескомпилированных веток селектор тредов.
![image](https://user-images.githubusercontent.com/76079492/193939282-968d3fc0-9af6-427e-b936-d82842774c66.png)
![image](https://user-images.githubusercontent.com/76079492/193939535-edd0bf12-2e80-42f7-9a07-0808a868424b.png)
![image](https://user-images.githubusercontent.com/76079492/193939614-4a0c323b-ab85-4508-8c64-05f444e4f5fc.png)

2022-10-04 22:40 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +невооружённым глазом видно, что все ресурсы компьютера уходят именно на саму обработку
Согласен, некорректно проанализировал этот момент. На GC тратится 5% ресурсов, кажется, что не так уж и много, хотя можем попробовать вместо G1 использовать Z1, время отклика будет меньше, но пропускать через систему сможем меньше запросов. Помимо трети CPU на NativeSocket.write() можно отследить закономерность, что при увеличении Krps увеличивается частота флашей, и на 50Krps (перегрузка) они происходят буквально каждую секунду, а если поставить chunktime меньше, чем 1с, то есть вероятность увидеть флаши ещё чаще, чем раз в секунду. Естественным образом раздувается пул потоков, которые выполняют эти флаши (стоит помнить, что

2022-10-04 23:24 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +Видно, что при заданных путах повышение латенси наблюдается в районе 95 перцентилей.
GC достаточно активно работает, ведь система перегружена. Он как раз расходует порядка 5% ресурсов CPU.

2022-10-05 16:08 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +когда как повышая нагрузку на систему, становится очевидным, что головка на диске не успевает так
Неактуально из-за смены реализации, в новом отчёте напишу про это.

2022-10-05 16:23 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/MyService.java
> +        this.server.registerShutdownHook();
Рекомендую почитать JavaDoc к `Runtime.getRuntime().addShutdownHook()` -- все эти хуки (после каждого `stop()`) вызовутся при остановке JVM.

2022-10-05 16:36 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +    Latency     1.32ms    1.24ms  33.15ms   95.69%
Здесь не "происходит компиляция селектор треда", а просто работает JIT -- видите, у них обоих родитель `all`? Краснота точки говорит о количестве сэмплов в окне в 20мс, т.е. об интенсивности использования CPU. В данном случае, я бы подумал скорее в сторону GC, но это нужно проверять включением логов GC.

2022-10-05 16:45 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +Одним из решений этой проблемы является перенос самого по себе диапазона ключей в мета-информацию
Да, интересная идея. Если не ошибаюсь, что-то подобное упоминал Фёдор в конце своей лекции про LSM, когда описывал гибридные стратегии compaction.
На практике в целях оптимизации прыжков по файлам (когда BloomFilter "пропустил" запрос внутрь SSTable) используются сэмплированные индексы ключей -- это рассматривалось в лекции про Cassandra.

2022-10-05 16:54 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +На 10к уже наблюдем "подзахлёб", когда среднее латенси становится больше 1мс:
Что именно в профиле указывает на "компиляцией ранее нескомпилированных веток селектор тредов"? Видно, что работает JIT, а также часть CPU тратит `SelectorThread` через `NativeSocket.write()`, который в итоге крутится в ядре на spin lock.

2022-10-05 16:55 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +невооружённым глазом видно, что все ресурсы компьютера уходят именно на саму обработку
Вы имели в виду ZGC, а не Z1, верно?

2022-10-05 18:44 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +когда как повышая нагрузку на систему, становится очевидным, что головка на диске не успевает так
В одной и той же хтмльке находятся геты, долбящие по одинаковым/разным/существующим/несуществующим ключам, из-за этого при обращении к такому набору хитмап приходится держать в голове, какая после какой следует, что не всегда возможно, да и просто бессмысленно. Сейчас дописываю новый отчёт, в котором на каждую такую вариацию гета будет сделана отдельная хтмлька.

2022-10-05 20:24 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +невооружённым глазом видно, что все ресурсы компьютера уходят именно на саму обработку
Верно

2022-10-05 20:41 UTC, PaaavelZ commented
Наконец-то дописал отчёт. Извините, что так поздно, писал весь вечер без остановки :)

2022-10-05 21:57 UTC, PaaavelZ commented on src/main/java/ok/dht/test/kovalenko/MyService.java
> +        this.server.registerShutdownHook();
Больше не хукаю.

2022-10-06 13:47 UTC, incubos approved these changes
14 баллов.

2022-10-06 13:47 UTC, incubos commented on src/main/java/ok/dht/test/kovalenko/stage1_report/Report.md
> +На 5Krps мы даже ускорились.
Как объяснить ускорение?

2022-10-07 12:56 UTC, incubos requested changes
Не проходит новые тесты. Пофиксите?

2022-10-07 13:42 UTC, PaaavelZ commented
> Не проходит новые тесты. Пофиксите?
Исправил

2022-10-11 09:32 UTC, merged