Stage 3 Dergunov Nikita
polis-vk/2022-highload-dht pull request #56
Opened 2022-10-23 19:32 UTC by nikita17th

2022-10-24 11:04 UTC, incubos requested changes
Есть ряд вопросов и замечаний.

2022-10-24 11:04 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/results/stage3/report.md
> +HeatMapы имеют не однородную раскраску в следствие локов потоков, количество которых сильно возросло с прошлым этапом,
Можете пояснить, откуда взялись дополнительные потоки? Можно ли уменьшить их число?

2022-10-24 11:04 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/results/stage3/report.md
> +Вывод wrk при 10000 rps
БОльшую нагрузку на чтение мы не держим?

2022-11-10 14:00 UTC, incubos commented
Здесь ожидать исправлений или оцениваем как есть?

2022-11-13 18:17 UTC, nikita17th commented
Добррого времени суток, видимо оенивать как есть, на данный момент не могу найти время, чтобы успевать заниматься на курсе в полном объеме.

2022-11-22 15:35 UTC, incubos commented
10 баллов.

2022-11-22 15:35 UTC, closed without merging