Lutsenko Dmitrii Stage2
polis-vk/2022-highload-dht pull request #59
Opened 2022-10-04 18:24 UTC by LutsenkoDm

2022-10-05 19:03 UTC, Artyomcool requested changes

2022-10-05 19:03 UTC, Artyomcool commented on src/main/java/ok/dht/test/lutsenko/reports/Stage2-report.md
> +      21% - синхронизация при изъятии задачи внутри блокирующей очереди в Executor (ArrayBlockingQueue.take)
Выглядит как будто бы это очень много.

2022-10-08 17:21 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/async-profiler/stage2/async-discard-get-lock.html
> +<!DOCTYPE html>
Сделал  flame graph и heatmap для локов

2022-10-08 17:21 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/DemoService.java
> +            Files.createDirectory(config.workingDir());
Убрал

2022-10-08 17:24 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/DemoService.java
> +    private ThreadPoolExecutor requestExecutor;
Исправил на ExecutorService, final здесь был невозможен так как при повторном старте сервера executor будет shutdown и придется его пересоздавать, но сейчас сделал final так как  requestExecutor мигрировал в отдельный класс сервера

2022-10-08 17:25 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/DemoService.java
> +import static ok.dht.test.lutsenko.service.ServiceUtils.uncheckedSendResponse;
Извиняюсь, импортировал через idea. Исправил везде

2022-10-08 17:25 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/ServiceUtils.java
> +            if (!executorService.awaitTermination(Integer.MAX_VALUE, TimeUnit.MILLISECONDS)) {
Сделано

2022-10-08 17:26 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/ServiceUtils.java
> +                throw new RuntimeException("Await termination too long");
Сделал,  RuntimeException заменил на TimeoutException, который обрабатывается в stop

2022-10-08 17:27 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/ServiceUtils.java
> +            throw new UncheckedIOException(e);
Переделал обработку ошибок в данном методе

2022-10-08 17:28 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/RequestExecutorService.java
> +            e.execute(r);
Да, но так сделано в стандартной DiscardOldestPolicy из ThreadPoolExecutor, на который я ориентировался

2022-10-08 17:29 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/RequestExecutorService.java
> +            e.execute(r);
Это решил оставить, добавил еще вариант со стеком

2022-10-08 17:29 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/service/RequestExecutorService.java
> +                new ArrayBlockingQueue<>(QUEUE_CAPACITY),
Добавил вариант со стеком

2022-10-08 17:30 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/wrk/scripts/stage1_GET.lua
> +end
Смотрю не один раз, но данные файлы смотрел по диагонали и не заметил

2022-10-08 17:30 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/wrk/scripts/stage1_PUT.lua
> +end
Исправил

2022-10-08 17:31 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/Stage2-report.md
> +На всех heatMap сначала идут 3 случая для PUT запросов(1, 10, 64 потока и соединения), затем 3 случая для GET запросов
Переделал на отдельные хитмапы

2022-10-08 17:31 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/Stage2-report.md
> +ThreadPoolExecutor, разве что использовать неблокирующую очередь для задач в ThreadPoolExecutor, если это возможно.
Дополнил в отчете

2022-10-08 17:32 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/Stage2-report.md
> +      21% - синхронизация при изъятии задачи внутри блокирующей очереди в Executor (ArrayBlockingQueue.take)
Сделал выбор потоков для executor на основании Runtime.getRuntime().availableProcessors()
Уменьшилось в 3 раза

2022-10-10 13:32 UTC, Artyomcool commented on src/main/java/ok/dht/test/lutsenko/reports/Stage2-report.md
> +      21% - синхронизация при изъятии задачи внутри блокирующей очереди в Executor (ArrayBlockingQueue.take)
Всё равно много

2022-10-10 13:33 UTC, Artyomcool commented on src/main/java/ok/dht/test/lutsenko/reports/Stage2-report.md
> +      21% - синхронизация при изъятии задачи внутри блокирующей очереди в Executor (ArrayBlockingQueue.take)
У вас потоки тратят время на сражение, кто следующий возьмёт задачу на исполнение. Ваш сервис должен заниматься этим?)

2022-10-11 23:14 UTC, LutsenkoDm commented on src/main/java/ok/dht/test/lutsenko/reports/Stage2-report.md
> +      21% - синхронизация при изъятии задачи внутри блокирующей очереди в Executor (ArrayBlockingQueue.take)
Оказалось, что большое значение для take() в данном случае связано не с конкуренцией потоков, а с тем, что очередь бывает пустой в определенные моменты времени, соответственно происходит блокировка. Чтобы этого избежать я поднял rate: до 16000 для PUT запросов и 8000 для GET и данное значение упало до пары процентов. Также уменьшал число потоков в executor до 1 со старым rate, но процент для take() был около 7%. Получается, что уменьшение этого процента при уменьшении числа потоков связано с тем, что очередь больше времени будет не пустая из-за того, что меньше потоков будет её обслуживать (если число потоков в executor лежит в пределах availableProcessors(), что с большой вероятностью исключит конкуренцию между потоками). 
Хитмапы и результаты профилирования обновил.

2022-10-17 18:17 UTC, Artyomcool commented on src/main/java/ok/dht/test/lutsenko/dao/StringUtils.java
> +        StringBuilder stringBuilder = new StringBuilder(str.substring(0, i));
просто случайно обратил внимание: вот тут, внезапно, JiT может убрать лишнюю аллокацию строки с помощью escape-анализа

2022-10-17 18:30 UTC, Artyomcool approved these changes
13 баллов.
Ход мыслей в целом корректный, но неучитывает того, что вы фактически не выходите за пределы page-кэша операционной системы, поэтому всё такое шустрое.
Контр-интуитивные результаты профилирования должны наталкивать на мысль, а точно ли оно сделано корректно.

2022-10-17 18:30 UTC, Artyomcool commented on src/main/java/ok/dht/test/lutsenko/reports/Stage2-report.md
> +      19.75% - обработка самого запроса, из которых 10% - добавление задачи в очередь для Executor,
10% на добавление в очередь? это явно не нормально

2022-10-17 18:31 UTC, merged