Trofimov Artyom | Stage 2
polis-vk/2022-highload-dht pull request #63
Opened 2022-10-24 17:48 UTC by artem24630

2022-10-26 09:03 UTC, incubos requested changes
Нужно зарезолвить конфликты.

2022-10-26 10:26 UTC, artem24630 commented
> Нужно зарезолвить конфликты.

готово

2022-10-27 08:13 UTC, atimofeyev requested changes

2022-10-27 08:13 UTC, atimofeyev commented on src/main/java/ok/dht/test/trofimov/MyService.java
> +                new ThreadPoolExecutor.DiscardOldestPolicy());
Не подходящий полиси для нашей задачи, нам надо отправить ошибку клиенту, а в текущей реализации мы просто заскипаем обработку и сессия уже отвалится по таймауту, непонятно когда

2022-10-27 16:21 UTC, artem24630 commented on src/main/java/ok/dht/test/trofimov/MyService.java
> +        requestsExecutor.shutdownNow();
переделал

2022-10-27 16:21 UTC, artem24630 commented on src/main/java/ok/dht/test/trofimov/MyService.java
>          server.stop();
хорошо, поменял

2022-10-27 16:22 UTC, artem24630 commented on src/main/java/ok/dht/test/trofimov/MyService.java
> +                new ThreadPoolExecutor.DiscardOldestPolicy());
поменял на AbortPolicy и отправляю клиентам ошибку

2022-10-31 12:31 UTC, atimofeyev approved these changes

2022-10-31 15:49 UTC, artem24630 commented
@atimofeyev какое кол-во баллов у меня за этот stage?

2022-10-31 20:39 UTC, atimofeyev commented
7 баллов

2022-11-02 09:16 UTC, merged