Trofimov Artyom | Stage 3
polis-vk/2022-highload-dht pull request #64
Opened 2022-10-24 17:49 UTC by artem24630

2022-10-26 09:02 UTC, incubos requested changes
Нужно зарезолвить конфликты.

2022-10-26 10:29 UTC, artem24630 commented
> Нужно зарезолвить конфликты.

готово

2022-10-28 08:57 UTC, atimofeyev requested changes

2022-10-28 08:57 UTC, atimofeyev commented on src/main/java/ok/dht/test/trofimov/MyService.java
> +                new ThreadPoolExecutor.DiscardOldestPolicy());
здесь я вижу те же самые проблемы что были в стейдж 2, давай сюда фиксы перенесем тоже

2022-10-28 08:57 UTC, atimofeyev commented on src/main/java/ok/dht/test/trofimov/MyService.java
> +            int hash = Hash.murmur3(url) + Hash.murmur3(key);
1. не совсем понял что это за алгоритм
2. слишком дорого такое будет делать на каждый запрос, хорошо бы все как-то преподсчитать

2022-10-29 08:43 UTC, artem24630 commented on src/main/java/ok/dht/test/trofimov/MyService.java
> +            int hash = Hash.murmur3(url) + Hash.murmur3(key);
Это rendezvous hashing.
предпосчитал хэши для clusterUrls, теперь должно быть не так дорого

2022-10-29 08:43 UTC, artem24630 commented on src/main/java/ok/dht/test/trofimov/MyService.java
> +                new ThreadPoolExecutor.DiscardOldestPolicy());
перенес

2022-10-31 12:36 UTC, atimofeyev commented on src/main/java/ok/dht/test/trofimov/MyService.java
> +            int hash = Hash.murmur3(url) + Hash.murmur3(key);
Но реализация похоже на некорректную, тут же для всех ключей будет выбираться один и тот же хост

2022-11-01 15:20 UTC, artem24630 commented on src/main/java/ok/dht/test/trofimov/MyService.java
> +            int hash = Hash.murmur3(url) + Hash.murmur3(key);
ну murmur довольно хорошо распределена, так что не будет один и тот же хост

2022-11-02 07:15 UTC, artem24630 commented on src/main/java/ok/dht/test/trofimov/MyService.java
> +            int hash = Hash.murmur3(url) + Hash.murmur3(key);
а, понял, почему некорректно:  по сути сейчас выбирается нода с максимальным хэшом, и хэш ключа не влияет на результат почти(кроме случаев переполнения)

2022-11-02 08:12 UTC, atimofeyev approved these changes

2022-11-02 08:13 UTC, atimofeyev commented
7 баллов

2022-11-02 09:17 UTC, incubos requested changes
Нужно зарезолвить конфликты перед merge.

2022-11-02 11:29 UTC, artem24630 commented
> Нужно зарезолвить конфликты перед merge.

готово

2022-11-03 11:28 UTC, merged