Stage 1 Kondraev Dmitry
polis-vk/2022-highload-dht pull request #66
Opened 2022-10-05 13:20 UTC by mariohuq

Отчет см. в [stage-01-http-api.md](src/main/java/ok/dht/test/kondraev/reports/stage-01-http-api.md).

Пропущен дедлайн.

2022-10-05 17:10 UTC, incubos commented
> Пропущен дедлайн.

Тогда 0 баллов, но всё равно будем мёрджить, как пофиксите оставшееся замечание от CodeClimate.

2022-10-05 17:10 UTC, incubos requested changes
Не все чеки проходят.

2022-10-06 14:38 UTC, incubos requested changes
Хорошее решение, но есть ряд вопросов и не хватает предложений по улучшению.

2022-10-06 14:38 UTC, incubos commented on src/main/java/ok/dht/test/kondraev/Server.java
> +    final Dao dao;
Почему не `private`?

2022-10-06 14:38 UTC, incubos commented on src/main/java/ok/dht/test/kondraev/reports/stage-01-http-api.md
> +![Put](01/Histogram-put.png)
Не хватает этого файла.

2022-10-06 14:38 UTC, incubos commented on src/main/java/ok/dht/test/kondraev/reports/stage-01-http-api.md
> +![Get](01/Histogram-get.png)
Не хватает этого файла.

2022-10-06 14:38 UTC, incubos commented on src/main/java/ok/dht/test/kondraev/reports/stage-01-http-api.md
> +- интервал профилирования стоит уменьшить (сейчас это `10ms`).
Что на это указывает? Почему не уменьшили?

2022-10-06 14:38 UTC, incubos commented on src/main/java/ok/dht/test/kondraev/reports/stage-01-http-api.md
> +- [get-02-alloc.html](01/get-01-alloc.html)
Чем отличаются `get-01-*` и `get-02-*`?

2022-10-06 14:38 UTC, incubos commented on src/main/java/ok/dht/test/kondraev/reports/stage-01-http-api.md
> +- значительная часть GET занимает доступ к диску через MemorySegment и его создание
Есть какие-то идеи по оптимизации?

2022-10-06 14:38 UTC, incubos commented on src/main/java/ok/dht/test/kondraev/reports/stage-01-http-api.md
> +![Get](01/Histogram-put-2.png)
Нет такого файла.

2022-10-06 14:38 UTC, incubos commented on src/main/java/ok/dht/test/kondraev/reports/stage-01-http-api.md
> +Распределение latency для GET:
Нет такого файла.

2022-10-06 14:38 UTC, incubos commented on src/main/java/ok/dht/test/kondraev/reports/stage-01-http-api.md
> +- не угадали со стабильной частотой запросов в обоих случаях.
Можете пояснить мысль?

2022-10-06 14:56 UTC, mariohuq commented on src/main/java/ok/dht/test/kondraev/reports/stage-01-http-api.md
> +![Put](01/Histogram-put.png)
Пропустил при коммите, добавлю этот и другие

2022-10-07 12:58 UTC, incubos requested changes
Не проходят новые тесты. Ждать доработок по замечаниям?

2022-10-07 12:59 UTC, mariohuq commented
@incubos да, я поправлю и доотвечу

2022-10-13 09:14 UTC, incubos commented
6 баллов.

2022-10-13 09:14 UTC, merged