[STAGE 2] Vihnin Fedor
polis-vk/2022-highload-dht pull request #66
Opened 2022-10-24 18:02 UTC by Brat-vseznamus

2022-11-12 21:25 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/vihnin/resources/report/stage2/ОТЧЕТ.md
> +1. Можем заметить, что с 85% до %15 от общей работы упало участие SelectorThread-a, что и привело к повышению
Немного нарушена причинно-следственная связь. Всё же это "70%" никуда не исчезли, мы просто переложили работу за обработку запросов с `SelectorThread` на `ExecutorService`. 
Хотелось бы услышать больше конкретики: что могло привести к ускорению?

2022-11-12 21:25 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/vihnin/resources/report/stage2/ОТЧЕТ.md
> +
Есть что сказать про локи?

2022-11-30 21:19 UTC, Brat-vseznamus commented on src/main/java/ok/dht/test/vihnin/resources/report/stage2/ОТЧЕТ.md
> +1. Можем заметить, что с 85% до %15 от общей работы упало участие SelectorThread-a, что и привело к повышению
Ну ускорение произошло из-за того, что теперь селектор тред, который ранее выполнял и функции обработчика запросов и принимающего этих запросов, остался только с выполнением тасок на прием запросов и отправку уже обработанных нами ответов. То есть теперь в освободившиеся время каждый селектор тред может принять побольше запросов, пока те будут выполнять параллельно другими воркерами. Ну пример простой: пусть у нас селектор тред и он раньше принимал за время T 1 запрос, обрабатывал его сам и отвечал. Теперь он сам делать ничего не будет, а примет например 5 запросов, которые почти идеально вместе начнут выполняться, и по итогу он за старый промежуток времени сообщит ответы не 1 пользователю, а например 2 или 3, произошло ускорение (цифры абстрактные, но главное что работа с базой больше занимает явно времени чем принятие запроса и отправка ответа, так что из-за параллельности данных процессов наблюдаем выигрыш)

2022-11-30 21:19 UTC, Brat-vseznamus commented on src/main/java/ok/dht/test/vihnin/resources/report/stage2/ОТЧЕТ.md
> +
Ну локи теперь в основном (t4_c64_R20000_get_lock.html) теперь происходят между тредами обработчиками, что и закономерно, они теперь больше  работают с ресурсом и больше тасок на себя берут по производительности)

2022-12-01 17:23 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/vihnin/ParallelHttpServer.java
> +        executorService.shutdown();
Я здесь хотел сказать, что после `shutdown()` стоило бы немного подождать с `awaitTermination()`, чтобы меньше тасок пришлось обрывать.

2022-12-01 17:25 UTC, Mr-Ravil commented on src/main/java/ok/dht/test/vihnin/resources/report/stage2/ОТЧЕТ.md
> +1. Можем заметить, что с 85% до %15 от общей работы упало участие SelectorThread-a, что и привело к повышению
Да, именно это я и хотел услышать, а то в отчёте было слишком размыто и поверхностно.

2022-12-01 17:27 UTC, Mr-Ravil commented
Можешь разрешить конфликты мержа?

2022-12-01 20:02 UTC, Brat-vseznamus commented
> Можешь разрешить конфликты мержа?

да, конечно

2022-12-08 12:27 UTC, incubos requested changes
Перед merge необходимо устранить конфликты.

2022-12-13 16:27 UTC, Mr-Ravil commented
необходимо разрешить конфликты

2022-12-22 15:25 UTC, Mr-Ravil approved these changes

2022-12-23 20:19 UTC, merged