Stage 2 Dergunov Nikita
polis-vk/2022-highload-dht pull request #72
Opened 2022-10-05 16:39 UTC by nikita17th

2022-10-07 14:26 UTC, incubos commented
В PR не должно быть бинарных архивов типа [html_results.zip](https://github.com/polis-vk/2022-highload-dht/pull/72/files#diff-ecdbeb1e90def40a04ede9ec5638be9fb76987ade82eb1be0aa266f2a6d11778) -- только отдельные файлы.

2022-10-07 14:45 UTC, incubos requested changes
Есть ряд вопросов и замечаний. Кроме того, не хватает интерактивных heat maps для анализа.

2022-10-07 14:45 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/results/stage2/report.md
> +* Обработка put запроса занимает 50 % времени процессора
Можно детальнее, пожалуйста?

2022-10-07 14:45 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/results/stage2/report.md
> +* Работа с пулом потоков 18 % времени
На что именно расходуется CPU? Т.е. в 3 раза больше, чем сам upsert?

2022-10-07 14:45 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/results/stage2/report.md
> +* 62 % алолокаций идет на чтение запроса
На что именно? Создание `Request`?

2022-10-07 14:45 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/results/stage2/report.md
> +* 33 % аллокаций идет на обработку put
Можно детальнее?

2022-10-07 14:45 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/results/stage2/report.md
> +* upsert в базу данных около 0.72 %
Суть `put` заключается в `upsert`, который ничего не стоит в плане аллокаций?

2022-10-07 14:45 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/results/stage2/report.md
> +* 33 % локов идет на чтение запроса
На что именно?

2022-10-07 14:45 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/results/stage2/report.md
> +* 50 % локов идет на работу с очередью запросов
Можно детальнее с указанием методов и классов?

2022-10-07 14:45 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/results/stage2/report.md
> +* Обработка get проса занимает 57 % времени процессора
Можно детальнее? На что именно расходуем ресурсы?

2022-10-07 14:45 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/results/stage2/report.md
> +* Работа с пулом потоков 15 % времени
Что за работа?

2022-10-07 14:45 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/results/stage2/report.md
> +* SelectorThread one.nio 16 % времени
Чем он занимается в этих 16%?

2022-10-07 14:45 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/results/stage2/report.md
> +* get в базу данных около 15 %
Что именно выделяем столько памяти?

2022-10-07 14:45 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/results/stage2/report.md
> +* 62 % алолокаций идет на чтение запроса
Можно что-то соптимизировать?

2022-10-07 14:45 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/results/stage2/report.md
> +* 33 % аллокаций идет на обработку get
Помимо "get в базу" ниже? Что именно аллоцирует память?

2022-10-07 14:45 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/results/stage2/report.md
> +* 32 % локов идет на чтение запроса
На чём мы блокируемся?

2022-10-07 14:45 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/results/stage2/report.md
> +* 50 % локов идет на работу с очередью запросов
Как это можно улучшить?

2022-10-07 14:45 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/scripts/get.lua
> +    wrk.body = "value" .. id
Зачем body в `GET`?

2022-10-07 14:45 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/HttpServerImpl.java
> +    private static final Set<Integer> SUPPORTED_METHODS = new HashSet<>(Arrays.asList(METHOD_GET, METHOD_PUT,
`Set.of()`?

2022-10-07 14:45 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/HttpServerImpl.java
> +    private static final int SIZE_QUEUE = 128;
Почему такое значение? Пробовали ли другие?

2022-10-07 14:45 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/HttpServerImpl.java
> +    private static final int COUNT_CORES = 6;
А если сделать больше? Ведь у вас NVME с большим параллелизмом?

2022-10-07 14:51 UTC, incubos commented on src/main/java/ok/dht/test/dergunov/HttpServerImpl.java
> +        poolExecutor.execute(() -> {
Очередь ограничена, а обработки `RejectedExecutionException` нет.

2022-10-12 21:35 UTC, nikita17th commented on src/main/java/ok/dht/test/dergunov/HttpServerImpl.java
> +            new ArrayBlockingQueue<>(SIZE_QUEUE)
Попробовал  LinkedBlockingQueue ,  в отчете написал сравнение, но больших преимуществ одной над другой не обнаружил, использую именно очередь так как запросы на которыъ проихводятся анализ не выделяются какими то большими, то есть нет запросов с размером данных 100 мегабйт

2022-10-12 21:36 UTC, nikita17th commented on src/main/java/ok/dht/test/dergunov/HttpServerImpl.java
> +    private static final int COUNT_CORES = 6;
Попробовал и больше и меньше в отчете приложил результаты, оказалось что при меньшем количестве работает лучше)

2022-10-12 21:36 UTC, nikita17th commented on src/main/java/ok/dht/test/dergunov/HttpServerImpl.java
> +    private static final int SIZE_QUEUE = 128;
Попробовал отипсал в отчете

2022-10-12 21:50 UTC, nikita17th commented on src/main/java/ok/dht/test/dergunov/results/stage2/report.md
> +* 62 % алолокаций идет на чтение запроса
Можно попробовать переопределить метод processHttpBuffer)

2022-10-12 21:55 UTC, nikita17th commented on src/main/java/ok/dht/test/dergunov/results/stage2/report.md
> +* get в базу данных около 15 %
На аллокации  MappedMemorySegmentImpl,  ктоорые используются при нахождении записи в базе данных

2022-10-12 22:55 UTC, nikita17th commented on src/main/java/ok/dht/test/dergunov/results/stage2/report.md
> +* 62 % алолокаций идет на чтение запроса
Да, в основном именно работа с методом parseRequest, в котором происходит создание Request

2022-10-13 09:17 UTC, incubos commented
14 баллов.

2022-10-13 09:17 UTC, merged