Galeev Artur Stage4
polis-vk/2022-highload-dht pull request #72
Opened 2022-10-24 20:59 UTC by coradead

2022-10-27 10:03 UTC, atimofeyev requested changes

2022-10-27 10:03 UTC, atimofeyev commented on src/main/java/ok/dht/test/galeev/DemoService.java
> +            node.put(header.getKey(), currentTime, request.getBody()).thenAccept((isSuccessful) -> {
тут очень хорошо виден копипаст по работе с репликами, можно было бы его как-то вынести в одно место, а в гет/пут/делете использоваться какие-то свои хендлеры

2022-10-27 10:11 UTC, coradead commented on src/main/java/ok/dht/test/galeev/AckBarrier.java
> +            continueBarrier.await();
У нас у всех запросов есть таймаут

2022-10-27 10:12 UTC, coradead commented on src/main/java/ok/dht/test/galeev/ConsistentHashRouter.java
> +                nodeList.add(vnode.getPhysicalNode());
Если я правильно понял: мы не решаем проблему остановки и запуска нод, главное чтобы остановка одной ноды не аффектила на другие

2022-10-27 10:13 UTC, coradead commented on src/main/java/ok/dht/test/galeev/DemoService.java
> +        proxyExecutor = Executors.newFixedThreadPool(8);
По числу ядер

2022-10-27 10:15 UTC, coradead commented on src/main/java/ok/dht/test/galeev/CustomHttpServer.java
> +        for (SelectorThread thread : selectors) {
На лекции сказали, что в начале надо закрыть сервер, а уж потом работников

2022-10-27 12:18 UTC, coradead commented on src/main/java/ok/dht/test/galeev/CustomHttpServer.java
> +            String id = request.getParameter("id=");
Исправил. Согласен, это все же бизнес логика, и, как оказалось, я дважды делал getParametr

2022-10-27 12:20 UTC, coradead commented on src/main/java/ok/dht/test/galeev/DemoService.java
> +            node.put(header.getKey(), currentTime, request.getBody()).thenAccept((isSuccessful) -> {
Если я правильно понял, то я исправил. Вынес одинаковый consumer у put и delete в метод.

2022-10-27 12:56 UTC, atimofeyev commented on src/main/java/ok/dht/test/galeev/ConsistentHashRouter.java
> +                nodeList.add(vnode.getPhysicalNode());
так остановка ноды будет аффектить другие - пойдут запросы на какую-то левую ноду
и если это пут - то там появятся данные которые не должны появиться

2022-10-27 12:58 UTC, atimofeyev commented on src/main/java/ok/dht/test/galeev/AckBarrier.java
> +            continueBarrier.await();
запросы то с таймаутом, а вот тут ожидание без таймаута, 
Если что-то пойдет не по плану, например какая-то бага, то тут зависнет на долго

2022-10-27 13:03 UTC, coradead commented on src/main/java/ok/dht/test/galeev/ConsistentHashRouter.java
> +                nodeList.add(vnode.getPhysicalNode());
Так ведь из списка не удаляются мертвые ноды. У них флажок, что они мертвые просто.

2022-10-27 13:06 UTC, atimofeyev commented on src/main/java/ok/dht/test/galeev/CustomHttpServer.java
> +        for (SelectorThread thread : selectors) {
я думаю говорили про то чтобы сначала перестать принимать запросы, потом остановить воркеров
если мы сначала закроем сервер то воркеры уже не смогут отдать ответ

2022-10-27 13:09 UTC, atimofeyev commented on src/main/java/ok/dht/test/galeev/ConsistentHashRouter.java
> +                nodeList.add(vnode.getPhysicalNode());
ага, хорошо, это я тупанул

2022-10-27 13:16 UTC, coradead commented on src/main/java/ok/dht/test/galeev/CustomHttpServer.java
> +        for (SelectorThread thread : selectors) {
Нам надо закрывать сокеты иначе тесты не пройдут

2022-10-27 13:16 UTC, atimofeyev commented
Тесты еще надо поправить

2022-10-27 13:17 UTC, coradead commented on src/main/java/ok/dht/test/galeev/CustomHttpServer.java
> +        for (SelectorThread thread : selectors) {
А у остановленных acceptor thread'ов нельзя закрыть сокеты

2022-10-27 13:18 UTC, coradead commented on src/main/java/ok/dht/test/galeev/Node.java
> +        public Entry<Timestamp, byte[]> getDao(String key) {
Это я пофиксил

2022-10-27 13:20 UTC, coradead commented on src/main/java/ok/dht/test/galeev/AckBarrier.java
> +            continueBarrier.await();
Окей, исправлю, как доберусь до дома. Я просто подумал зачем здесь дублирующий тайм-аут. Мне стоит тайм-аут и тут и там(при создании реквеста указывается в билдере) оставить или только здесь?

2022-10-28 07:46 UTC, atimofeyev commented on src/main/java/ok/dht/test/galeev/CustomHttpServer.java
> +        for (SelectorThread thread : selectors) {
Так я же не про AcceptorThread а про Worker-ы.
надо было комментарий оставить в DemoService
сейчас там такой порядок
server.stop();
workersExecutor.shutdown();
proxyExecutor.shutdown();
localNode.stop();

А должен быть такой:
stoping = true;
workersExecutor.shutdown();
server.stop();
proxyExecutor.shutdown();
localNode.stop();

В реальной жизни вместо stoping=true сервер выведется из ротации и к нему уже не пойдут новые запросы, в нашем же случае можно на все входящие запросы в статусе stoping сразу отдавать ответ об ошибке. Но все полученные ране запросы лучше обработать корректно, может мы уже вставили в базу значение, лучше вернуть клиенту ответ 200 чем ничего не отдать, если мы сначала закроем сокет

2022-10-28 07:50 UTC, atimofeyev commented on src/main/java/ok/dht/test/galeev/AckBarrier.java
> +            continueBarrier.await();
пусть везде будут )

2022-10-28 08:07 UTC, atimofeyev commented on src/main/java/ok/dht/test/galeev/DemoService.java
> +            node.put(header.getKey(), currentTime, request.getBody()).thenAccept((isSuccessful) -> {
Не совсем, остался копипаст более высокого порядка, а именно логика работы с ответом от нескольких реплик, она в общем должна быть общая, а переопределяем мы только кусок логики, я говорил о том что сделать как-то так

`    private interface Handler {
        CompletableFuture action(Node node);
        void responseOk();
        void responseError();
        void onSucces();
        void onError();
    }

    private class Router {
        private AckBarrier barier;
        private ConsistentHashRouter router;

        private void doIt(Handler handler) {
            for(Node node : nodes) {
                handler.action(node).thenAccept(){
                    if (success) {
                        handler.onSucces();
                    } else {
                        handler.onError();
                    }
                };
            }
            barrier.wait();
            if (barier.isOk()) {
                handler.responseOk();
            } else {
                handler.responseError();;
            }
        }
    }`

2022-10-29 15:27 UTC, coradead commented on src/main/java/ok/dht/test/galeev/DemoService.java
> +            node.put(header.getKey(), currentTime, request.getBody()).thenAccept((isSuccessful) -> {
Вроде исправил, как вы и написали. Ну +-

2022-10-29 15:27 UTC, coradead commented on src/main/java/ok/dht/test/galeev/AckBarrier.java
> +            continueBarrier.await();
Сделано!

2022-10-29 15:28 UTC, coradead commented on src/main/java/ok/dht/test/galeev/CustomHttpServer.java
> +        for (SelectorThread thread : selectors) {
Сделано!

2022-10-31 12:19 UTC, atimofeyev commented on src/main/java/ok/dht/test/galeev/CustomHttpServer.java
> +        isStopping = true;
кстати можно было и без переменной обойтись, так как все равно все задачи мы шедьюлим в экзекутер, после вызова shutdown() на екзекутере воркера он и так будет сразу кидать ошибку. Но в общем не принципиально

2022-10-31 12:20 UTC, atimofeyev approved these changes

2022-10-31 12:29 UTC, atimofeyev requested changes

2022-10-31 12:29 UTC, atimofeyev commented on src/main/java/ok/dht/test/galeev/CustomHttpServer.java
> +            return;
тут стоит ответить ошибкой, а не просто проигнорировать

2022-10-31 12:35 UTC, coradead commented on src/main/java/ok/dht/test/galeev/CustomHttpServer.java
> +            return;
Так у меня изначально вокреры стопались раньше

2022-10-31 12:36 UTC, coradead commented on src/main/java/ok/dht/test/galeev/CustomHttpServer.java
> +            return;
В DemoService 81 строка

2022-10-31 12:38 UTC, coradead commented on src/main/java/ok/dht/test/galeev/CustomHttpServer.java
> +            return;
Еще с прошого стейджа

2022-10-31 21:13 UTC, atimofeyev commented on src/main/java/ok/dht/test/galeev/CustomHttpServer.java
> +            return;
Да, только изначально было не в том порядке, сейчас все хорошо, вот только ретурн не на месте, не должно быть необработанных запросов. Либо ошибка либо ответ

2022-10-31 21:14 UTC, coradead commented on src/main/java/ok/dht/test/galeev/CustomHttpServer.java
> +            return;
А какую ошибку выбрать?

2022-11-01 20:47 UTC, coradead commented on src/main/java/ok/dht/test/galeev/CustomHttpServer.java
> +            return;
Все. Дошло. Я думал  кидать exception и не мог понять как это может помочь. А щас дошло, что вы про ответ клиенту говорили

2022-11-01 20:49 UTC, coradead commented on src/main/java/ok/dht/test/galeev/CustomHttpServer.java
> +            return;
Я сделал ``session.sendError(Response.SERVICE_UNAVAILABLE, "Server is shutting down");```

2022-11-01 20:55 UTC, coradead commented on src/main/java/ok/dht/test/galeev/CustomHttpServer.java
> +            return;
Так же хотел бы уточнить, а подойдет ли подобное решение в качестве решения 5 стейджа?

2022-11-02 08:34 UTC, atimofeyev requested changes

2022-11-02 08:34 UTC, atimofeyev commented on src/main/java/ok/dht/test/galeev/Node.java
> +                    isAlive = false;
а когда нода пометится как живая? вдруг была просто случайная ошибка?

2022-11-02 08:34 UTC, atimofeyev commented on src/main/java/ok/dht/test/galeev/CustomHttpServer.java
> +            return;
да, похоже что решение сойдет и для пятого этапа

2022-11-02 08:38 UTC, coradead commented on src/main/java/ok/dht/test/galeev/Node.java
> +                    isAlive = false;
Так мы никогда не узнаем, что с ней случилось, но влиять на другие она начинает сразу

2022-11-02 08:45 UTC, atimofeyev approved these changes

2022-11-02 08:45 UTC, atimofeyev commented
15 баллов

2022-11-02 09:14 UTC, merged