Stage 2 Yasevich Artem
polis-vk/2022-highload-dht pull request #80
Opened 2022-10-05 18:25 UTC by a-yasevich

2022-10-07 15:47 UTC, incubos requested changes
Есть множество вопросов и замечаний.

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/profiling/stage2/report.md
> +В среднем задержки получились те же, но они получили более равномерное распределение. Нет запросов, которым не повезло, и до которых рабочие потоки добираются не сразу.
"Нет запросов, которым не повезло, и до которых рабочие потоки добираются не сразу." -- это точно будет видно на среднем времени ответа?

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/profiling/stage2/report.md
> +* Среднюю задержку в `1.31ms` для put запросов. Что говорит, что на этих цифрах сервер уже "напрягается"
Давайте сконцентрируем анализ на перцентилях, а не на среднем?

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/profiling/stage2/report.md
> +* На `Lock` видим 58% сэмплов queue.take(), 23% queue.size() и 15% queue.offer()
Откуда `queue.size()`?

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/profiling/stage2/report.md
> +* На `CPU` видим 15% сэмплов queue.take(), 1.76% queue.offer(), 0.74% queue.size()
Откуда `queue.size()`?

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/AlmostLifoQueue.java
> +public class AlmostLifoQueue extends LinkedBlockingDeque<Runnable> {
Не хватает JavaDoc с описанием поведения примитива.

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/AlmostLifoQueue.java
> +    public AlmostLifoQueue(int capacity, int fifoRareness) {
Без изучения кода названия `fifoRareness` мало о чём говорит.

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/AlmostLifoQueue.java
> +    public AlmostLifoQueue(int capacity, int fifoRareness) {
Не хватает валидации `fifoRareness`.

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/AlmostLifoQueue.java
> +        if (retrievedElements.incrementAndGet() % fifoRareness != 0) {
Это выражение повторяется во всех метода. Давайте отрефакторим в `private` метод?

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/AlmostLifoQueue.java
> +public class AlmostLifoQueue extends LinkedBlockingDeque<Runnable> {
Сейчас зашита `LinkedBlockingDeque` реализация и другие легко не потестировать. Делегат был бы лучше наследования, потому что позволяют принимать `BlockingDeque` и экспериментировать с разными реализациями.

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/profiling/stage2/report.md
> +Не видим снижения производительности ввиду эффекта, обсуждаемого на занятии, когда пока мы обрабатывали запросы, следующие затаймаутились, обработав их, затаймаутились следующие.
Этот эффект будет видно только на перегруженной системе, верно? У вас возникала перегрузка? Если очередь почти всегда пуста, то `fifoRareness` ни на что не влияет ведь?

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/profiling/stage2/report.md
> +Видим, что средние задержки примерно те же, но при этом их распределение не такое равномерное, и при 99.9% мы видим резкий скачок.
Что значит "распределение средних задержек"? Можете привести конкретные цифры?

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/profiling/stage2/report.md
> +Появляются потоки, которые блокируются на очереди
Где мы это видим?

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/profiling/stage2/report.md
> +Подтверждение мы видим при профилировании:
Разве это не говорит лишь о том, что очередь интенсивно используется? Как это подтверждает эффект, описанный выше?

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/profiling/stage2/report.md
> +* задержки для put в перегруженном режиме уменьшились в два раза
Можно цифры?

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/profiling/stage2/report.md
> +* для get видим уменьшение средней задержки и более равномерное распределение
Хотелось бы увидеть цифры и не изучать сырые данные -- это же отчёт с анализом.

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/ServiceImpl.java
> +        server.addRequestHandlers(this);
Лучше сначала `addRequestHandlers()`, а затем `start()`. Обсуждали на прошлом занятии.

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/ServiceImpl.java
> +        private static final int CPUs = Runtime.getRuntime().availableProcessors();
Другие значения пробовали? У вас же ещё на CPU работают селекторы, да и диск SSD или NVMe?

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/ServiceImpl.java
> +        private final BlockingQueue<Runnable> queue = new AlmostLifoQueue(POOL_QUEUE_SIZE, FIFO_RARENESS);
Другие реализации очередей помимо `LinkedBlockingDeque` пробовали?

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/ServiceImpl.java
> +            return queue.size() >= POOL_QUEUE_SIZE;
Так не работает, потому что код вызывается из кучи потоков. Лучше ловить `RejectedExecutionException`.

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/ServiceImpl.java
> +            return queue.size() >= POOL_QUEUE_SIZE;
А может быть больше `POOL_QUEUE_SIZE`?

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/ServiceImpl.java
> +                    throw new RuntimeException(e);
Кто это поймает и обработает? Клиент так и останется висеть и ожидать ответа?

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/ServiceImpl.java
> +                throw new RuntimeException(e);
Выше это никто не ловит и не обрабатывает.

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/ServiceImpl.java
> +            dao.upsert(new BaseEntry<>(fromString(id), null));
Не хватает обработки ошибок.

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/ServiceImpl.java
> +        private Response handlePost(String id, Request request) {
`handlePut()`?

2022-10-07 15:47 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/ServiceImpl.java
> +            dao.upsert(new BaseEntry<>(fromString(id), MemorySegment.ofArray(request.getBody())));
Не хватает обработки ошибок.

2022-10-10 09:49 UTC, a-yasevich commented on src/main/java/ok/dht/test/yasevich/AlmostLifoQueue.java
> +public class AlmostLifoQueue extends LinkedBlockingDeque<Runnable> {
Для для реализации этого класса хотелось бы иметь BlockingDeque, реализация которого вроде бы одна - LinkedBlockingDeque, поэтому решил, что нормально воспользоваться наследованием

2022-10-10 09:50 UTC, a-yasevich commented on src/main/java/ok/dht/test/yasevich/AlmostLifoQueue.java
> +    public AlmostLifoQueue(int capacity, int fifoRareness) {
Лучшего названия не получилось придумать :)

2022-10-10 09:57 UTC, a-yasevich commented on src/main/java/ok/dht/test/yasevich/profiling/stage2/report.md
> +* На `Lock` видим 58% сэмплов queue.take(), 23% queue.size() и 15% queue.offer()
Для каждого запроса спрашивали явно спрашивали у очереди её размер. Поменял это на catch RejectedExecutionException, передал тест №1 из отчёта,  теперь на графе не видно метода queue.size()

2022-10-11 09:51 UTC, incubos commented
Переводите на меня, когда закончите с исправлениями.

2022-10-12 11:13 UTC, incubos approved these changes
14 баллов.

2022-10-12 11:13 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/ServiceImpl.java
> +                        sendResponse(session, response);
Если здесь произойдёт ошибка, то в `catch` мы ещё раз отправим HTTP response и сломаем HTTP connection, верно?

2022-10-12 11:13 UTC, incubos commented on src/main/java/ok/dht/test/yasevich/profiling/stage2/report.md
> +большей части бледно-розовая.
Ох уж эти 50 оттенков розового...

2022-10-13 09:18 UTC, merged